apiVersion: graph.cosmo.crossplane.io/v1alpha1
kind: Contract
metadata:
  annotations:
    meta.upbound.io/example-id: graph/v1alpha1/contract
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    excludeTags: ${var.exclude_tags}
    includeTags: ${var.include_tags}
    name: ${var.name}
    namespaceSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    routingUrl: ${var.routing_url}
    sourceSelector:
      matchLabels:
        testing.upbound.io/example-name: example
