apiVersion: graph.cosmo.m.crossplane.io/v1alpha1
kind: RouterToken
metadata:
  annotations:
    meta.upbound.io/example-id: graph/v1alpha1/routertoken
  labels:
    testing.upbound.io/example-name: test
  name: test
  namespace: crossplane-system
spec:
  forProvider:
    graphSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    name: ${var.name}
    namespaceSelector:
      matchLabels:
        testing.upbound.io/example-name: example
