apiVersion: graph.cosmo.m.crossplane.io/v1alpha1
kind: CosmoNamespace
metadata:
  name: example
  namespace: crossplane-system
  labels:
    testing.upbound.io/example-name: example
spec:
  forProvider:
    name: crossplane-example
  providerConfigRef:
    kind: ProviderConfig
    name: default
---
apiVersion: graph.cosmo.m.crossplane.io/v1alpha1
kind: FederatedGraph
metadata:
  name: example
  namespace: crossplane-system
  labels:
    testing.upbound.io/example-name: example
spec:
  forProvider:
    name: example-graph
    routingUrl: http://router.example.com/graphql
    labelMatchers:
      - team=example
    namespaceSelector:
      matchLabels:
        testing.upbound.io/example-name: example
  providerConfigRef:
    kind: ProviderConfig
    name: default
---
apiVersion: graph.cosmo.m.crossplane.io/v1alpha1
kind: Subgraph
metadata:
  name: example
  namespace: crossplane-system
  labels:
    testing.upbound.io/example-name: example
spec:
  forProvider:
    name: example-subgraph
    routingUrl: http://subgraph.example.com/graphql
    labels:
      team: example
    schema: |
      type Query {
        hello: String
      }
    namespaceSelector:
      matchLabels:
        testing.upbound.io/example-name: example
  providerConfigRef:
    kind: ProviderConfig
    name: default
---
apiVersion: graph.cosmo.m.crossplane.io/v1alpha1
kind: RouterToken
metadata:
  name: example
  namespace: crossplane-system
  labels:
    testing.upbound.io/example-name: example
spec:
  forProvider:
    name: example-router-token
    graphSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    namespaceSelector:
      matchLabels:
        testing.upbound.io/example-name: example
  providerConfigRef:
    kind: ProviderConfig
    name: default
  writeConnectionSecretToRef:
    name: example-router-token
