//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/crossplane/crossplane/apis/v2/core/v2"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Contract) DeepCopyInto(out *Contract) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Contract.
func (in *Contract) DeepCopy() *Contract {
	if in == nil {
		return nil
	}
	out := new(Contract)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Contract) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContractInitParameters) DeepCopyInto(out *ContractInitParameters) {
	*out = *in
	if in.AdmissionWebhookSecretSecretRef != nil {
		in, out := &in.AdmissionWebhookSecretSecretRef, &out.AdmissionWebhookSecretSecretRef
		*out = new(v2.LocalSecretKeySelector)
		**out = **in
	}
	if in.AdmissionWebhookURL != nil {
		in, out := &in.AdmissionWebhookURL, &out.AdmissionWebhookURL
		*out = new(string)
		**out = **in
	}
	if in.ExcludeTags != nil {
		in, out := &in.ExcludeTags, &out.ExcludeTags
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.IncludeTags != nil {
		in, out := &in.IncludeTags, &out.IncludeTags
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Namespace != nil {
		in, out := &in.Namespace, &out.Namespace
		*out = new(string)
		**out = **in
	}
	if in.NamespaceRef != nil {
		in, out := &in.NamespaceRef, &out.NamespaceRef
		*out = new(v2.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.NamespaceSelector != nil {
		in, out := &in.NamespaceSelector, &out.NamespaceSelector
		*out = new(v2.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Readme != nil {
		in, out := &in.Readme, &out.Readme
		*out = new(string)
		**out = **in
	}
	if in.RoutingURL != nil {
		in, out := &in.RoutingURL, &out.RoutingURL
		*out = new(string)
		**out = **in
	}
	if in.Source != nil {
		in, out := &in.Source, &out.Source
		*out = new(string)
		**out = **in
	}
	if in.SourceRef != nil {
		in, out := &in.SourceRef, &out.SourceRef
		*out = new(v2.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.SourceSelector != nil {
		in, out := &in.SourceSelector, &out.SourceSelector
		*out = new(v2.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.SupportsFederation != nil {
		in, out := &in.SupportsFederation, &out.SupportsFederation
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContractInitParameters.
func (in *ContractInitParameters) DeepCopy() *ContractInitParameters {
	if in == nil {
		return nil
	}
	out := new(ContractInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContractList) DeepCopyInto(out *ContractList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Contract, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContractList.
func (in *ContractList) DeepCopy() *ContractList {
	if in == nil {
		return nil
	}
	out := new(ContractList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ContractList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContractObservation) DeepCopyInto(out *ContractObservation) {
	*out = *in
	if in.AdmissionWebhookURL != nil {
		in, out := &in.AdmissionWebhookURL, &out.AdmissionWebhookURL
		*out = new(string)
		**out = **in
	}
	if in.ExcludeTags != nil {
		in, out := &in.ExcludeTags, &out.ExcludeTags
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.IncludeTags != nil {
		in, out := &in.IncludeTags, &out.IncludeTags
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Namespace != nil {
		in, out := &in.Namespace, &out.Namespace
		*out = new(string)
		**out = **in
	}
	if in.Readme != nil {
		in, out := &in.Readme, &out.Readme
		*out = new(string)
		**out = **in
	}
	if in.RoutingURL != nil {
		in, out := &in.RoutingURL, &out.RoutingURL
		*out = new(string)
		**out = **in
	}
	if in.Source != nil {
		in, out := &in.Source, &out.Source
		*out = new(string)
		**out = **in
	}
	if in.SupportsFederation != nil {
		in, out := &in.SupportsFederation, &out.SupportsFederation
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContractObservation.
func (in *ContractObservation) DeepCopy() *ContractObservation {
	if in == nil {
		return nil
	}
	out := new(ContractObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContractParameters) DeepCopyInto(out *ContractParameters) {
	*out = *in
	if in.AdmissionWebhookSecretSecretRef != nil {
		in, out := &in.AdmissionWebhookSecretSecretRef, &out.AdmissionWebhookSecretSecretRef
		*out = new(v2.LocalSecretKeySelector)
		**out = **in
	}
	if in.AdmissionWebhookURL != nil {
		in, out := &in.AdmissionWebhookURL, &out.AdmissionWebhookURL
		*out = new(string)
		**out = **in
	}
	if in.ExcludeTags != nil {
		in, out := &in.ExcludeTags, &out.ExcludeTags
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.IncludeTags != nil {
		in, out := &in.IncludeTags, &out.IncludeTags
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Namespace != nil {
		in, out := &in.Namespace, &out.Namespace
		*out = new(string)
		**out = **in
	}
	if in.NamespaceRef != nil {
		in, out := &in.NamespaceRef, &out.NamespaceRef
		*out = new(v2.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.NamespaceSelector != nil {
		in, out := &in.NamespaceSelector, &out.NamespaceSelector
		*out = new(v2.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Readme != nil {
		in, out := &in.Readme, &out.Readme
		*out = new(string)
		**out = **in
	}
	if in.RoutingURL != nil {
		in, out := &in.RoutingURL, &out.RoutingURL
		*out = new(string)
		**out = **in
	}
	if in.Source != nil {
		in, out := &in.Source, &out.Source
		*out = new(string)
		**out = **in
	}
	if in.SourceRef != nil {
		in, out := &in.SourceRef, &out.SourceRef
		*out = new(v2.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.SourceSelector != nil {
		in, out := &in.SourceSelector, &out.SourceSelector
		*out = new(v2.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.SupportsFederation != nil {
		in, out := &in.SupportsFederation, &out.SupportsFederation
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContractParameters.
func (in *ContractParameters) DeepCopy() *ContractParameters {
	if in == nil {
		return nil
	}
	out := new(ContractParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContractSpec) DeepCopyInto(out *ContractSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContractSpec.
func (in *ContractSpec) DeepCopy() *ContractSpec {
	if in == nil {
		return nil
	}
	out := new(ContractSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContractStatus) DeepCopyInto(out *ContractStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContractStatus.
func (in *ContractStatus) DeepCopy() *ContractStatus {
	if in == nil {
		return nil
	}
	out := new(ContractStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CosmoNamespace) DeepCopyInto(out *CosmoNamespace) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CosmoNamespace.
func (in *CosmoNamespace) DeepCopy() *CosmoNamespace {
	if in == nil {
		return nil
	}
	out := new(CosmoNamespace)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CosmoNamespace) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CosmoNamespaceInitParameters) DeepCopyInto(out *CosmoNamespaceInitParameters) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CosmoNamespaceInitParameters.
func (in *CosmoNamespaceInitParameters) DeepCopy() *CosmoNamespaceInitParameters {
	if in == nil {
		return nil
	}
	out := new(CosmoNamespaceInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CosmoNamespaceList) DeepCopyInto(out *CosmoNamespaceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CosmoNamespace, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CosmoNamespaceList.
func (in *CosmoNamespaceList) DeepCopy() *CosmoNamespaceList {
	if in == nil {
		return nil
	}
	out := new(CosmoNamespaceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CosmoNamespaceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CosmoNamespaceObservation) DeepCopyInto(out *CosmoNamespaceObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CosmoNamespaceObservation.
func (in *CosmoNamespaceObservation) DeepCopy() *CosmoNamespaceObservation {
	if in == nil {
		return nil
	}
	out := new(CosmoNamespaceObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CosmoNamespaceParameters) DeepCopyInto(out *CosmoNamespaceParameters) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CosmoNamespaceParameters.
func (in *CosmoNamespaceParameters) DeepCopy() *CosmoNamespaceParameters {
	if in == nil {
		return nil
	}
	out := new(CosmoNamespaceParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CosmoNamespaceSpec) DeepCopyInto(out *CosmoNamespaceSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CosmoNamespaceSpec.
func (in *CosmoNamespaceSpec) DeepCopy() *CosmoNamespaceSpec {
	if in == nil {
		return nil
	}
	out := new(CosmoNamespaceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CosmoNamespaceStatus) DeepCopyInto(out *CosmoNamespaceStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CosmoNamespaceStatus.
func (in *CosmoNamespaceStatus) DeepCopy() *CosmoNamespaceStatus {
	if in == nil {
		return nil
	}
	out := new(CosmoNamespaceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FeatureFlag) DeepCopyInto(out *FeatureFlag) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FeatureFlag.
func (in *FeatureFlag) DeepCopy() *FeatureFlag {
	if in == nil {
		return nil
	}
	out := new(FeatureFlag)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FeatureFlag) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FeatureFlagInitParameters) DeepCopyInto(out *FeatureFlagInitParameters) {
	*out = *in
	if in.FeatureSubgraphs != nil {
		in, out := &in.FeatureSubgraphs, &out.FeatureSubgraphs
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.FeatureSubgraphsRefs != nil {
		in, out := &in.FeatureSubgraphsRefs, &out.FeatureSubgraphsRefs
		*out = make([]v2.NamespacedReference, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.FeatureSubgraphsSelector != nil {
		in, out := &in.FeatureSubgraphsSelector, &out.FeatureSubgraphsSelector
		*out = new(v2.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.IsEnabled != nil {
		in, out := &in.IsEnabled, &out.IsEnabled
		*out = new(bool)
		**out = **in
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Namespace != nil {
		in, out := &in.Namespace, &out.Namespace
		*out = new(string)
		**out = **in
	}
	if in.NamespaceRef != nil {
		in, out := &in.NamespaceRef, &out.NamespaceRef
		*out = new(v2.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.NamespaceSelector != nil {
		in, out := &in.NamespaceSelector, &out.NamespaceSelector
		*out = new(v2.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FeatureFlagInitParameters.
func (in *FeatureFlagInitParameters) DeepCopy() *FeatureFlagInitParameters {
	if in == nil {
		return nil
	}
	out := new(FeatureFlagInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FeatureFlagList) DeepCopyInto(out *FeatureFlagList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FeatureFlag, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FeatureFlagList.
func (in *FeatureFlagList) DeepCopy() *FeatureFlagList {
	if in == nil {
		return nil
	}
	out := new(FeatureFlagList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FeatureFlagList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FeatureFlagObservation) DeepCopyInto(out *FeatureFlagObservation) {
	*out = *in
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = new(string)
		**out = **in
	}
	if in.CreatedBy != nil {
		in, out := &in.CreatedBy, &out.CreatedBy
		*out = new(string)
		**out = **in
	}
	if in.FeatureSubgraphs != nil {
		in, out := &in.FeatureSubgraphs, &out.FeatureSubgraphs
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.IsEnabled != nil {
		in, out := &in.IsEnabled, &out.IsEnabled
		*out = new(bool)
		**out = **in
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Namespace != nil {
		in, out := &in.Namespace, &out.Namespace
		*out = new(string)
		**out = **in
	}
	if in.UpdatedAt != nil {
		in, out := &in.UpdatedAt, &out.UpdatedAt
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FeatureFlagObservation.
func (in *FeatureFlagObservation) DeepCopy() *FeatureFlagObservation {
	if in == nil {
		return nil
	}
	out := new(FeatureFlagObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FeatureFlagParameters) DeepCopyInto(out *FeatureFlagParameters) {
	*out = *in
	if in.FeatureSubgraphs != nil {
		in, out := &in.FeatureSubgraphs, &out.FeatureSubgraphs
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.FeatureSubgraphsRefs != nil {
		in, out := &in.FeatureSubgraphsRefs, &out.FeatureSubgraphsRefs
		*out = make([]v2.NamespacedReference, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.FeatureSubgraphsSelector != nil {
		in, out := &in.FeatureSubgraphsSelector, &out.FeatureSubgraphsSelector
		*out = new(v2.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.IsEnabled != nil {
		in, out := &in.IsEnabled, &out.IsEnabled
		*out = new(bool)
		**out = **in
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Namespace != nil {
		in, out := &in.Namespace, &out.Namespace
		*out = new(string)
		**out = **in
	}
	if in.NamespaceRef != nil {
		in, out := &in.NamespaceRef, &out.NamespaceRef
		*out = new(v2.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.NamespaceSelector != nil {
		in, out := &in.NamespaceSelector, &out.NamespaceSelector
		*out = new(v2.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FeatureFlagParameters.
func (in *FeatureFlagParameters) DeepCopy() *FeatureFlagParameters {
	if in == nil {
		return nil
	}
	out := new(FeatureFlagParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FeatureFlagSpec) DeepCopyInto(out *FeatureFlagSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FeatureFlagSpec.
func (in *FeatureFlagSpec) DeepCopy() *FeatureFlagSpec {
	if in == nil {
		return nil
	}
	out := new(FeatureFlagSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FeatureFlagStatus) DeepCopyInto(out *FeatureFlagStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FeatureFlagStatus.
func (in *FeatureFlagStatus) DeepCopy() *FeatureFlagStatus {
	if in == nil {
		return nil
	}
	out := new(FeatureFlagStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FeatureSubgraph) DeepCopyInto(out *FeatureSubgraph) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FeatureSubgraph.
func (in *FeatureSubgraph) DeepCopy() *FeatureSubgraph {
	if in == nil {
		return nil
	}
	out := new(FeatureSubgraph)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FeatureSubgraph) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FeatureSubgraphInitParameters) DeepCopyInto(out *FeatureSubgraphInitParameters) {
	*out = *in
	if in.BaseSubgraphName != nil {
		in, out := &in.BaseSubgraphName, &out.BaseSubgraphName
		*out = new(string)
		**out = **in
	}
	if in.BaseSubgraphRef != nil {
		in, out := &in.BaseSubgraphRef, &out.BaseSubgraphRef
		*out = new(v2.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.BaseSubgraphSelector != nil {
		in, out := &in.BaseSubgraphSelector, &out.BaseSubgraphSelector
		*out = new(v2.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Namespace != nil {
		in, out := &in.Namespace, &out.Namespace
		*out = new(string)
		**out = **in
	}
	if in.NamespaceRef != nil {
		in, out := &in.NamespaceRef, &out.NamespaceRef
		*out = new(v2.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.NamespaceSelector != nil {
		in, out := &in.NamespaceSelector, &out.NamespaceSelector
		*out = new(v2.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Readme != nil {
		in, out := &in.Readme, &out.Readme
		*out = new(string)
		**out = **in
	}
	if in.RoutingURL != nil {
		in, out := &in.RoutingURL, &out.RoutingURL
		*out = new(string)
		**out = **in
	}
	if in.Schema != nil {
		in, out := &in.Schema, &out.Schema
		*out = new(string)
		**out = **in
	}
	if in.SubscriptionProtocol != nil {
		in, out := &in.SubscriptionProtocol, &out.SubscriptionProtocol
		*out = new(string)
		**out = **in
	}
	if in.SubscriptionURL != nil {
		in, out := &in.SubscriptionURL, &out.SubscriptionURL
		*out = new(string)
		**out = **in
	}
	if in.WebsocketSubprotocol != nil {
		in, out := &in.WebsocketSubprotocol, &out.WebsocketSubprotocol
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FeatureSubgraphInitParameters.
func (in *FeatureSubgraphInitParameters) DeepCopy() *FeatureSubgraphInitParameters {
	if in == nil {
		return nil
	}
	out := new(FeatureSubgraphInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FeatureSubgraphList) DeepCopyInto(out *FeatureSubgraphList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FeatureSubgraph, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FeatureSubgraphList.
func (in *FeatureSubgraphList) DeepCopy() *FeatureSubgraphList {
	if in == nil {
		return nil
	}
	out := new(FeatureSubgraphList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FeatureSubgraphList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FeatureSubgraphObservation) DeepCopyInto(out *FeatureSubgraphObservation) {
	*out = *in
	if in.BaseSubgraphName != nil {
		in, out := &in.BaseSubgraphName, &out.BaseSubgraphName
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Namespace != nil {
		in, out := &in.Namespace, &out.Namespace
		*out = new(string)
		**out = **in
	}
	if in.Readme != nil {
		in, out := &in.Readme, &out.Readme
		*out = new(string)
		**out = **in
	}
	if in.RoutingURL != nil {
		in, out := &in.RoutingURL, &out.RoutingURL
		*out = new(string)
		**out = **in
	}
	if in.Schema != nil {
		in, out := &in.Schema, &out.Schema
		*out = new(string)
		**out = **in
	}
	if in.SubscriptionProtocol != nil {
		in, out := &in.SubscriptionProtocol, &out.SubscriptionProtocol
		*out = new(string)
		**out = **in
	}
	if in.SubscriptionURL != nil {
		in, out := &in.SubscriptionURL, &out.SubscriptionURL
		*out = new(string)
		**out = **in
	}
	if in.WebsocketSubprotocol != nil {
		in, out := &in.WebsocketSubprotocol, &out.WebsocketSubprotocol
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FeatureSubgraphObservation.
func (in *FeatureSubgraphObservation) DeepCopy() *FeatureSubgraphObservation {
	if in == nil {
		return nil
	}
	out := new(FeatureSubgraphObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FeatureSubgraphParameters) DeepCopyInto(out *FeatureSubgraphParameters) {
	*out = *in
	if in.BaseSubgraphName != nil {
		in, out := &in.BaseSubgraphName, &out.BaseSubgraphName
		*out = new(string)
		**out = **in
	}
	if in.BaseSubgraphRef != nil {
		in, out := &in.BaseSubgraphRef, &out.BaseSubgraphRef
		*out = new(v2.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.BaseSubgraphSelector != nil {
		in, out := &in.BaseSubgraphSelector, &out.BaseSubgraphSelector
		*out = new(v2.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Namespace != nil {
		in, out := &in.Namespace, &out.Namespace
		*out = new(string)
		**out = **in
	}
	if in.NamespaceRef != nil {
		in, out := &in.NamespaceRef, &out.NamespaceRef
		*out = new(v2.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.NamespaceSelector != nil {
		in, out := &in.NamespaceSelector, &out.NamespaceSelector
		*out = new(v2.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Readme != nil {
		in, out := &in.Readme, &out.Readme
		*out = new(string)
		**out = **in
	}
	if in.RoutingURL != nil {
		in, out := &in.RoutingURL, &out.RoutingURL
		*out = new(string)
		**out = **in
	}
	if in.Schema != nil {
		in, out := &in.Schema, &out.Schema
		*out = new(string)
		**out = **in
	}
	if in.SubscriptionProtocol != nil {
		in, out := &in.SubscriptionProtocol, &out.SubscriptionProtocol
		*out = new(string)
		**out = **in
	}
	if in.SubscriptionURL != nil {
		in, out := &in.SubscriptionURL, &out.SubscriptionURL
		*out = new(string)
		**out = **in
	}
	if in.WebsocketSubprotocol != nil {
		in, out := &in.WebsocketSubprotocol, &out.WebsocketSubprotocol
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FeatureSubgraphParameters.
func (in *FeatureSubgraphParameters) DeepCopy() *FeatureSubgraphParameters {
	if in == nil {
		return nil
	}
	out := new(FeatureSubgraphParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FeatureSubgraphSpec) DeepCopyInto(out *FeatureSubgraphSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FeatureSubgraphSpec.
func (in *FeatureSubgraphSpec) DeepCopy() *FeatureSubgraphSpec {
	if in == nil {
		return nil
	}
	out := new(FeatureSubgraphSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FeatureSubgraphStatus) DeepCopyInto(out *FeatureSubgraphStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FeatureSubgraphStatus.
func (in *FeatureSubgraphStatus) DeepCopy() *FeatureSubgraphStatus {
	if in == nil {
		return nil
	}
	out := new(FeatureSubgraphStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FederatedGraph) DeepCopyInto(out *FederatedGraph) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FederatedGraph.
func (in *FederatedGraph) DeepCopy() *FederatedGraph {
	if in == nil {
		return nil
	}
	out := new(FederatedGraph)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FederatedGraph) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FederatedGraphInitParameters) DeepCopyInto(out *FederatedGraphInitParameters) {
	*out = *in
	if in.AdmissionWebhookSecretSecretRef != nil {
		in, out := &in.AdmissionWebhookSecretSecretRef, &out.AdmissionWebhookSecretSecretRef
		*out = new(v2.LocalSecretKeySelector)
		**out = **in
	}
	if in.AdmissionWebhookURL != nil {
		in, out := &in.AdmissionWebhookURL, &out.AdmissionWebhookURL
		*out = new(string)
		**out = **in
	}
	if in.LabelMatchers != nil {
		in, out := &in.LabelMatchers, &out.LabelMatchers
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Namespace != nil {
		in, out := &in.Namespace, &out.Namespace
		*out = new(string)
		**out = **in
	}
	if in.NamespaceRef != nil {
		in, out := &in.NamespaceRef, &out.NamespaceRef
		*out = new(v2.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.NamespaceSelector != nil {
		in, out := &in.NamespaceSelector, &out.NamespaceSelector
		*out = new(v2.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Readme != nil {
		in, out := &in.Readme, &out.Readme
		*out = new(string)
		**out = **in
	}
	if in.RoutingURL != nil {
		in, out := &in.RoutingURL, &out.RoutingURL
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FederatedGraphInitParameters.
func (in *FederatedGraphInitParameters) DeepCopy() *FederatedGraphInitParameters {
	if in == nil {
		return nil
	}
	out := new(FederatedGraphInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FederatedGraphList) DeepCopyInto(out *FederatedGraphList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FederatedGraph, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FederatedGraphList.
func (in *FederatedGraphList) DeepCopy() *FederatedGraphList {
	if in == nil {
		return nil
	}
	out := new(FederatedGraphList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FederatedGraphList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FederatedGraphObservation) DeepCopyInto(out *FederatedGraphObservation) {
	*out = *in
	if in.AdmissionWebhookURL != nil {
		in, out := &in.AdmissionWebhookURL, &out.AdmissionWebhookURL
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.LabelMatchers != nil {
		in, out := &in.LabelMatchers, &out.LabelMatchers
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Namespace != nil {
		in, out := &in.Namespace, &out.Namespace
		*out = new(string)
		**out = **in
	}
	if in.Readme != nil {
		in, out := &in.Readme, &out.Readme
		*out = new(string)
		**out = **in
	}
	if in.RoutingURL != nil {
		in, out := &in.RoutingURL, &out.RoutingURL
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FederatedGraphObservation.
func (in *FederatedGraphObservation) DeepCopy() *FederatedGraphObservation {
	if in == nil {
		return nil
	}
	out := new(FederatedGraphObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FederatedGraphParameters) DeepCopyInto(out *FederatedGraphParameters) {
	*out = *in
	if in.AdmissionWebhookSecretSecretRef != nil {
		in, out := &in.AdmissionWebhookSecretSecretRef, &out.AdmissionWebhookSecretSecretRef
		*out = new(v2.LocalSecretKeySelector)
		**out = **in
	}
	if in.AdmissionWebhookURL != nil {
		in, out := &in.AdmissionWebhookURL, &out.AdmissionWebhookURL
		*out = new(string)
		**out = **in
	}
	if in.LabelMatchers != nil {
		in, out := &in.LabelMatchers, &out.LabelMatchers
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Namespace != nil {
		in, out := &in.Namespace, &out.Namespace
		*out = new(string)
		**out = **in
	}
	if in.NamespaceRef != nil {
		in, out := &in.NamespaceRef, &out.NamespaceRef
		*out = new(v2.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.NamespaceSelector != nil {
		in, out := &in.NamespaceSelector, &out.NamespaceSelector
		*out = new(v2.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Readme != nil {
		in, out := &in.Readme, &out.Readme
		*out = new(string)
		**out = **in
	}
	if in.RoutingURL != nil {
		in, out := &in.RoutingURL, &out.RoutingURL
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FederatedGraphParameters.
func (in *FederatedGraphParameters) DeepCopy() *FederatedGraphParameters {
	if in == nil {
		return nil
	}
	out := new(FederatedGraphParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FederatedGraphSpec) DeepCopyInto(out *FederatedGraphSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FederatedGraphSpec.
func (in *FederatedGraphSpec) DeepCopy() *FederatedGraphSpec {
	if in == nil {
		return nil
	}
	out := new(FederatedGraphSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FederatedGraphStatus) DeepCopyInto(out *FederatedGraphStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FederatedGraphStatus.
func (in *FederatedGraphStatus) DeepCopy() *FederatedGraphStatus {
	if in == nil {
		return nil
	}
	out := new(FederatedGraphStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Monograph) DeepCopyInto(out *Monograph) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Monograph.
func (in *Monograph) DeepCopy() *Monograph {
	if in == nil {
		return nil
	}
	out := new(Monograph)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Monograph) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonographInitParameters) DeepCopyInto(out *MonographInitParameters) {
	*out = *in
	if in.AdmissionWebhookSecretSecretRef != nil {
		in, out := &in.AdmissionWebhookSecretSecretRef, &out.AdmissionWebhookSecretSecretRef
		*out = new(v2.LocalSecretKeySelector)
		**out = **in
	}
	if in.AdmissionWebhookURL != nil {
		in, out := &in.AdmissionWebhookURL, &out.AdmissionWebhookURL
		*out = new(string)
		**out = **in
	}
	if in.GraphURL != nil {
		in, out := &in.GraphURL, &out.GraphURL
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Namespace != nil {
		in, out := &in.Namespace, &out.Namespace
		*out = new(string)
		**out = **in
	}
	if in.NamespaceRef != nil {
		in, out := &in.NamespaceRef, &out.NamespaceRef
		*out = new(v2.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.NamespaceSelector != nil {
		in, out := &in.NamespaceSelector, &out.NamespaceSelector
		*out = new(v2.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Readme != nil {
		in, out := &in.Readme, &out.Readme
		*out = new(string)
		**out = **in
	}
	if in.RoutingURL != nil {
		in, out := &in.RoutingURL, &out.RoutingURL
		*out = new(string)
		**out = **in
	}
	if in.Schema != nil {
		in, out := &in.Schema, &out.Schema
		*out = new(string)
		**out = **in
	}
	if in.SubscriptionProtocol != nil {
		in, out := &in.SubscriptionProtocol, &out.SubscriptionProtocol
		*out = new(string)
		**out = **in
	}
	if in.SubscriptionURL != nil {
		in, out := &in.SubscriptionURL, &out.SubscriptionURL
		*out = new(string)
		**out = **in
	}
	if in.WebsocketSubprotocol != nil {
		in, out := &in.WebsocketSubprotocol, &out.WebsocketSubprotocol
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonographInitParameters.
func (in *MonographInitParameters) DeepCopy() *MonographInitParameters {
	if in == nil {
		return nil
	}
	out := new(MonographInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonographList) DeepCopyInto(out *MonographList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Monograph, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonographList.
func (in *MonographList) DeepCopy() *MonographList {
	if in == nil {
		return nil
	}
	out := new(MonographList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MonographList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonographObservation) DeepCopyInto(out *MonographObservation) {
	*out = *in
	if in.AdmissionWebhookURL != nil {
		in, out := &in.AdmissionWebhookURL, &out.AdmissionWebhookURL
		*out = new(string)
		**out = **in
	}
	if in.GraphURL != nil {
		in, out := &in.GraphURL, &out.GraphURL
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Namespace != nil {
		in, out := &in.Namespace, &out.Namespace
		*out = new(string)
		**out = **in
	}
	if in.Readme != nil {
		in, out := &in.Readme, &out.Readme
		*out = new(string)
		**out = **in
	}
	if in.RoutingURL != nil {
		in, out := &in.RoutingURL, &out.RoutingURL
		*out = new(string)
		**out = **in
	}
	if in.Schema != nil {
		in, out := &in.Schema, &out.Schema
		*out = new(string)
		**out = **in
	}
	if in.SubscriptionProtocol != nil {
		in, out := &in.SubscriptionProtocol, &out.SubscriptionProtocol
		*out = new(string)
		**out = **in
	}
	if in.SubscriptionURL != nil {
		in, out := &in.SubscriptionURL, &out.SubscriptionURL
		*out = new(string)
		**out = **in
	}
	if in.WebsocketSubprotocol != nil {
		in, out := &in.WebsocketSubprotocol, &out.WebsocketSubprotocol
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonographObservation.
func (in *MonographObservation) DeepCopy() *MonographObservation {
	if in == nil {
		return nil
	}
	out := new(MonographObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonographParameters) DeepCopyInto(out *MonographParameters) {
	*out = *in
	if in.AdmissionWebhookSecretSecretRef != nil {
		in, out := &in.AdmissionWebhookSecretSecretRef, &out.AdmissionWebhookSecretSecretRef
		*out = new(v2.LocalSecretKeySelector)
		**out = **in
	}
	if in.AdmissionWebhookURL != nil {
		in, out := &in.AdmissionWebhookURL, &out.AdmissionWebhookURL
		*out = new(string)
		**out = **in
	}
	if in.GraphURL != nil {
		in, out := &in.GraphURL, &out.GraphURL
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Namespace != nil {
		in, out := &in.Namespace, &out.Namespace
		*out = new(string)
		**out = **in
	}
	if in.NamespaceRef != nil {
		in, out := &in.NamespaceRef, &out.NamespaceRef
		*out = new(v2.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.NamespaceSelector != nil {
		in, out := &in.NamespaceSelector, &out.NamespaceSelector
		*out = new(v2.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Readme != nil {
		in, out := &in.Readme, &out.Readme
		*out = new(string)
		**out = **in
	}
	if in.RoutingURL != nil {
		in, out := &in.RoutingURL, &out.RoutingURL
		*out = new(string)
		**out = **in
	}
	if in.Schema != nil {
		in, out := &in.Schema, &out.Schema
		*out = new(string)
		**out = **in
	}
	if in.SubscriptionProtocol != nil {
		in, out := &in.SubscriptionProtocol, &out.SubscriptionProtocol
		*out = new(string)
		**out = **in
	}
	if in.SubscriptionURL != nil {
		in, out := &in.SubscriptionURL, &out.SubscriptionURL
		*out = new(string)
		**out = **in
	}
	if in.WebsocketSubprotocol != nil {
		in, out := &in.WebsocketSubprotocol, &out.WebsocketSubprotocol
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonographParameters.
func (in *MonographParameters) DeepCopy() *MonographParameters {
	if in == nil {
		return nil
	}
	out := new(MonographParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonographSpec) DeepCopyInto(out *MonographSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonographSpec.
func (in *MonographSpec) DeepCopy() *MonographSpec {
	if in == nil {
		return nil
	}
	out := new(MonographSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonographStatus) DeepCopyInto(out *MonographStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonographStatus.
func (in *MonographStatus) DeepCopy() *MonographStatus {
	if in == nil {
		return nil
	}
	out := new(MonographStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PersistedOperations) DeepCopyInto(out *PersistedOperations) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PersistedOperations.
func (in *PersistedOperations) DeepCopy() *PersistedOperations {
	if in == nil {
		return nil
	}
	out := new(PersistedOperations)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PersistedOperations) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PersistedOperationsInitParameters) DeepCopyInto(out *PersistedOperationsInitParameters) {
	*out = *in
	if in.ClientName != nil {
		in, out := &in.ClientName, &out.ClientName
		*out = new(string)
		**out = **in
	}
	if in.FederatedGraphName != nil {
		in, out := &in.FederatedGraphName, &out.FederatedGraphName
		*out = new(string)
		**out = **in
	}
	if in.FederatedGraphRef != nil {
		in, out := &in.FederatedGraphRef, &out.FederatedGraphRef
		*out = new(v2.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.FederatedGraphSelector != nil {
		in, out := &in.FederatedGraphSelector, &out.FederatedGraphSelector
		*out = new(v2.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Namespace != nil {
		in, out := &in.Namespace, &out.Namespace
		*out = new(string)
		**out = **in
	}
	if in.NamespaceRef != nil {
		in, out := &in.NamespaceRef, &out.NamespaceRef
		*out = new(v2.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.NamespaceSelector != nil {
		in, out := &in.NamespaceSelector, &out.NamespaceSelector
		*out = new(v2.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Operations != nil {
		in, out := &in.Operations, &out.Operations
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PersistedOperationsInitParameters.
func (in *PersistedOperationsInitParameters) DeepCopy() *PersistedOperationsInitParameters {
	if in == nil {
		return nil
	}
	out := new(PersistedOperationsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PersistedOperationsList) DeepCopyInto(out *PersistedOperationsList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PersistedOperations, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PersistedOperationsList.
func (in *PersistedOperationsList) DeepCopy() *PersistedOperationsList {
	if in == nil {
		return nil
	}
	out := new(PersistedOperationsList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PersistedOperationsList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PersistedOperationsObservation) DeepCopyInto(out *PersistedOperationsObservation) {
	*out = *in
	if in.ClientName != nil {
		in, out := &in.ClientName, &out.ClientName
		*out = new(string)
		**out = **in
	}
	if in.FederatedGraphName != nil {
		in, out := &in.FederatedGraphName, &out.FederatedGraphName
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Namespace != nil {
		in, out := &in.Namespace, &out.Namespace
		*out = new(string)
		**out = **in
	}
	if in.Operations != nil {
		in, out := &in.Operations, &out.Operations
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PersistedOperationsObservation.
func (in *PersistedOperationsObservation) DeepCopy() *PersistedOperationsObservation {
	if in == nil {
		return nil
	}
	out := new(PersistedOperationsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PersistedOperationsParameters) DeepCopyInto(out *PersistedOperationsParameters) {
	*out = *in
	if in.ClientName != nil {
		in, out := &in.ClientName, &out.ClientName
		*out = new(string)
		**out = **in
	}
	if in.FederatedGraphName != nil {
		in, out := &in.FederatedGraphName, &out.FederatedGraphName
		*out = new(string)
		**out = **in
	}
	if in.FederatedGraphRef != nil {
		in, out := &in.FederatedGraphRef, &out.FederatedGraphRef
		*out = new(v2.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.FederatedGraphSelector != nil {
		in, out := &in.FederatedGraphSelector, &out.FederatedGraphSelector
		*out = new(v2.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Namespace != nil {
		in, out := &in.Namespace, &out.Namespace
		*out = new(string)
		**out = **in
	}
	if in.NamespaceRef != nil {
		in, out := &in.NamespaceRef, &out.NamespaceRef
		*out = new(v2.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.NamespaceSelector != nil {
		in, out := &in.NamespaceSelector, &out.NamespaceSelector
		*out = new(v2.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Operations != nil {
		in, out := &in.Operations, &out.Operations
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PersistedOperationsParameters.
func (in *PersistedOperationsParameters) DeepCopy() *PersistedOperationsParameters {
	if in == nil {
		return nil
	}
	out := new(PersistedOperationsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PersistedOperationsSpec) DeepCopyInto(out *PersistedOperationsSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PersistedOperationsSpec.
func (in *PersistedOperationsSpec) DeepCopy() *PersistedOperationsSpec {
	if in == nil {
		return nil
	}
	out := new(PersistedOperationsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PersistedOperationsStatus) DeepCopyInto(out *PersistedOperationsStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PersistedOperationsStatus.
func (in *PersistedOperationsStatus) DeepCopy() *PersistedOperationsStatus {
	if in == nil {
		return nil
	}
	out := new(PersistedOperationsStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RouterToken) DeepCopyInto(out *RouterToken) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RouterToken.
func (in *RouterToken) DeepCopy() *RouterToken {
	if in == nil {
		return nil
	}
	out := new(RouterToken)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RouterToken) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RouterTokenInitParameters) DeepCopyInto(out *RouterTokenInitParameters) {
	*out = *in
	if in.GraphName != nil {
		in, out := &in.GraphName, &out.GraphName
		*out = new(string)
		**out = **in
	}
	if in.GraphRef != nil {
		in, out := &in.GraphRef, &out.GraphRef
		*out = new(v2.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.GraphSelector != nil {
		in, out := &in.GraphSelector, &out.GraphSelector
		*out = new(v2.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Namespace != nil {
		in, out := &in.Namespace, &out.Namespace
		*out = new(string)
		**out = **in
	}
	if in.NamespaceRef != nil {
		in, out := &in.NamespaceRef, &out.NamespaceRef
		*out = new(v2.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.NamespaceSelector != nil {
		in, out := &in.NamespaceSelector, &out.NamespaceSelector
		*out = new(v2.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RouterTokenInitParameters.
func (in *RouterTokenInitParameters) DeepCopy() *RouterTokenInitParameters {
	if in == nil {
		return nil
	}
	out := new(RouterTokenInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RouterTokenList) DeepCopyInto(out *RouterTokenList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RouterToken, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RouterTokenList.
func (in *RouterTokenList) DeepCopy() *RouterTokenList {
	if in == nil {
		return nil
	}
	out := new(RouterTokenList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RouterTokenList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RouterTokenObservation) DeepCopyInto(out *RouterTokenObservation) {
	*out = *in
	if in.GraphName != nil {
		in, out := &in.GraphName, &out.GraphName
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Namespace != nil {
		in, out := &in.Namespace, &out.Namespace
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RouterTokenObservation.
func (in *RouterTokenObservation) DeepCopy() *RouterTokenObservation {
	if in == nil {
		return nil
	}
	out := new(RouterTokenObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RouterTokenParameters) DeepCopyInto(out *RouterTokenParameters) {
	*out = *in
	if in.GraphName != nil {
		in, out := &in.GraphName, &out.GraphName
		*out = new(string)
		**out = **in
	}
	if in.GraphRef != nil {
		in, out := &in.GraphRef, &out.GraphRef
		*out = new(v2.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.GraphSelector != nil {
		in, out := &in.GraphSelector, &out.GraphSelector
		*out = new(v2.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Namespace != nil {
		in, out := &in.Namespace, &out.Namespace
		*out = new(string)
		**out = **in
	}
	if in.NamespaceRef != nil {
		in, out := &in.NamespaceRef, &out.NamespaceRef
		*out = new(v2.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.NamespaceSelector != nil {
		in, out := &in.NamespaceSelector, &out.NamespaceSelector
		*out = new(v2.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RouterTokenParameters.
func (in *RouterTokenParameters) DeepCopy() *RouterTokenParameters {
	if in == nil {
		return nil
	}
	out := new(RouterTokenParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RouterTokenSpec) DeepCopyInto(out *RouterTokenSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RouterTokenSpec.
func (in *RouterTokenSpec) DeepCopy() *RouterTokenSpec {
	if in == nil {
		return nil
	}
	out := new(RouterTokenSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RouterTokenStatus) DeepCopyInto(out *RouterTokenStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RouterTokenStatus.
func (in *RouterTokenStatus) DeepCopy() *RouterTokenStatus {
	if in == nil {
		return nil
	}
	out := new(RouterTokenStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Subgraph) DeepCopyInto(out *Subgraph) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Subgraph.
func (in *Subgraph) DeepCopy() *Subgraph {
	if in == nil {
		return nil
	}
	out := new(Subgraph)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Subgraph) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubgraphInitParameters) DeepCopyInto(out *SubgraphInitParameters) {
	*out = *in
	if in.IsEventDrivenGraph != nil {
		in, out := &in.IsEventDrivenGraph, &out.IsEventDrivenGraph
		*out = new(bool)
		**out = **in
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Namespace != nil {
		in, out := &in.Namespace, &out.Namespace
		*out = new(string)
		**out = **in
	}
	if in.NamespaceRef != nil {
		in, out := &in.NamespaceRef, &out.NamespaceRef
		*out = new(v2.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.NamespaceSelector != nil {
		in, out := &in.NamespaceSelector, &out.NamespaceSelector
		*out = new(v2.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Readme != nil {
		in, out := &in.Readme, &out.Readme
		*out = new(string)
		**out = **in
	}
	if in.RoutingURL != nil {
		in, out := &in.RoutingURL, &out.RoutingURL
		*out = new(string)
		**out = **in
	}
	if in.Schema != nil {
		in, out := &in.Schema, &out.Schema
		*out = new(string)
		**out = **in
	}
	if in.SubscriptionProtocol != nil {
		in, out := &in.SubscriptionProtocol, &out.SubscriptionProtocol
		*out = new(string)
		**out = **in
	}
	if in.SubscriptionURL != nil {
		in, out := &in.SubscriptionURL, &out.SubscriptionURL
		*out = new(string)
		**out = **in
	}
	if in.UnsetLabels != nil {
		in, out := &in.UnsetLabels, &out.UnsetLabels
		*out = new(bool)
		**out = **in
	}
	if in.WebsocketSubprotocol != nil {
		in, out := &in.WebsocketSubprotocol, &out.WebsocketSubprotocol
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubgraphInitParameters.
func (in *SubgraphInitParameters) DeepCopy() *SubgraphInitParameters {
	if in == nil {
		return nil
	}
	out := new(SubgraphInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubgraphList) DeepCopyInto(out *SubgraphList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Subgraph, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubgraphList.
func (in *SubgraphList) DeepCopy() *SubgraphList {
	if in == nil {
		return nil
	}
	out := new(SubgraphList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SubgraphList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubgraphObservation) DeepCopyInto(out *SubgraphObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.IsEventDrivenGraph != nil {
		in, out := &in.IsEventDrivenGraph, &out.IsEventDrivenGraph
		*out = new(bool)
		**out = **in
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Namespace != nil {
		in, out := &in.Namespace, &out.Namespace
		*out = new(string)
		**out = **in
	}
	if in.Readme != nil {
		in, out := &in.Readme, &out.Readme
		*out = new(string)
		**out = **in
	}
	if in.RoutingURL != nil {
		in, out := &in.RoutingURL, &out.RoutingURL
		*out = new(string)
		**out = **in
	}
	if in.Schema != nil {
		in, out := &in.Schema, &out.Schema
		*out = new(string)
		**out = **in
	}
	if in.SubscriptionProtocol != nil {
		in, out := &in.SubscriptionProtocol, &out.SubscriptionProtocol
		*out = new(string)
		**out = **in
	}
	if in.SubscriptionURL != nil {
		in, out := &in.SubscriptionURL, &out.SubscriptionURL
		*out = new(string)
		**out = **in
	}
	if in.UnsetLabels != nil {
		in, out := &in.UnsetLabels, &out.UnsetLabels
		*out = new(bool)
		**out = **in
	}
	if in.WebsocketSubprotocol != nil {
		in, out := &in.WebsocketSubprotocol, &out.WebsocketSubprotocol
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubgraphObservation.
func (in *SubgraphObservation) DeepCopy() *SubgraphObservation {
	if in == nil {
		return nil
	}
	out := new(SubgraphObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubgraphParameters) DeepCopyInto(out *SubgraphParameters) {
	*out = *in
	if in.IsEventDrivenGraph != nil {
		in, out := &in.IsEventDrivenGraph, &out.IsEventDrivenGraph
		*out = new(bool)
		**out = **in
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Namespace != nil {
		in, out := &in.Namespace, &out.Namespace
		*out = new(string)
		**out = **in
	}
	if in.NamespaceRef != nil {
		in, out := &in.NamespaceRef, &out.NamespaceRef
		*out = new(v2.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.NamespaceSelector != nil {
		in, out := &in.NamespaceSelector, &out.NamespaceSelector
		*out = new(v2.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Readme != nil {
		in, out := &in.Readme, &out.Readme
		*out = new(string)
		**out = **in
	}
	if in.RoutingURL != nil {
		in, out := &in.RoutingURL, &out.RoutingURL
		*out = new(string)
		**out = **in
	}
	if in.Schema != nil {
		in, out := &in.Schema, &out.Schema
		*out = new(string)
		**out = **in
	}
	if in.SubscriptionProtocol != nil {
		in, out := &in.SubscriptionProtocol, &out.SubscriptionProtocol
		*out = new(string)
		**out = **in
	}
	if in.SubscriptionURL != nil {
		in, out := &in.SubscriptionURL, &out.SubscriptionURL
		*out = new(string)
		**out = **in
	}
	if in.UnsetLabels != nil {
		in, out := &in.UnsetLabels, &out.UnsetLabels
		*out = new(bool)
		**out = **in
	}
	if in.WebsocketSubprotocol != nil {
		in, out := &in.WebsocketSubprotocol, &out.WebsocketSubprotocol
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubgraphParameters.
func (in *SubgraphParameters) DeepCopy() *SubgraphParameters {
	if in == nil {
		return nil
	}
	out := new(SubgraphParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubgraphSpec) DeepCopyInto(out *SubgraphSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubgraphSpec.
func (in *SubgraphSpec) DeepCopy() *SubgraphSpec {
	if in == nil {
		return nil
	}
	out := new(SubgraphSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubgraphStatus) DeepCopyInto(out *SubgraphStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubgraphStatus.
func (in *SubgraphStatus) DeepCopy() *SubgraphStatus {
	if in == nil {
		return nil
	}
	out := new(SubgraphStatus)
	in.DeepCopyInto(out)
	return out
}
