// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *Contract) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *CosmoNamespace) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *FeatureFlag) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *FeatureSubgraph) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *FederatedGraph) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Monograph) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *PersistedOperations) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *RouterToken) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Subgraph) Hub() {}
