// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type PersistedOperationsInitParameters struct {

	// (String) The name of the client the operations belong to (e.g. web, ios). The client is created on first publish.
	// The name of the client the operations belong to (e.g. `web`, `ios`). The client is created on first publish.
	ClientName *string `json:"clientName,omitempty" tf:"client_name,omitempty"`

	// (String) The name of the federated graph to register the operations on.
	// The name of the federated graph to register the operations on.
	// +crossplane:generate:reference:type=github.com/web-seven/provider-wundergraph-cosmo/apis/namespaced/graph/v1alpha1.FederatedGraph
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("name",false)
	// +crossplane:generate:reference:refFieldName=FederatedGraphRef
	// +crossplane:generate:reference:selectorFieldName=FederatedGraphSelector
	FederatedGraphName *string `json:"federatedGraphName,omitempty" tf:"federated_graph_name,omitempty"`

	// Reference to a FederatedGraph in graph to populate federatedGraphName.
	// +kubebuilder:validation:Optional
	FederatedGraphRef *v2.NamespacedReference `json:"federatedGraphRef,omitempty" tf:"-"`

	// Selector for a FederatedGraph in graph to populate federatedGraphName.
	// +kubebuilder:validation:Optional
	FederatedGraphSelector *v2.NamespacedSelector `json:"federatedGraphSelector,omitempty" tf:"-"`

	// (String) The namespace of the federated graph.
	// The namespace of the federated graph.
	// +crossplane:generate:reference:type=github.com/web-seven/provider-wundergraph-cosmo/apis/namespaced/graph/v1alpha1.CosmoNamespace
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("name",false)
	// +crossplane:generate:reference:refFieldName=NamespaceRef
	// +crossplane:generate:reference:selectorFieldName=NamespaceSelector
	Namespace *string `json:"namespace,omitempty" tf:"namespace,omitempty"`

	// Reference to a CosmoNamespace in graph to populate namespace.
	// +kubebuilder:validation:Optional
	NamespaceRef *v2.NamespacedReference `json:"namespaceRef,omitempty" tf:"-"`

	// Selector for a CosmoNamespace in graph to populate namespace.
	// +kubebuilder:validation:Optional
	NamespaceSelector *v2.NamespacedSelector `json:"namespaceSelector,omitempty" tf:"-"`

	// (Map of String) The persisted operations as a map of an arbitrary label to the contents of a plain GraphQL document. JSON manifests are not supported yet.
	// The persisted operations as a map of an arbitrary label to the contents of a plain GraphQL document. JSON manifests are not supported yet.
	// +mapType=granular
	Operations map[string]*string `json:"operations,omitempty" tf:"operations,omitempty"`
}

type PersistedOperationsObservation struct {

	// (String) The name of the client the operations belong to (e.g. web, ios). The client is created on first publish.
	// The name of the client the operations belong to (e.g. `web`, `ios`). The client is created on first publish.
	ClientName *string `json:"clientName,omitempty" tf:"client_name,omitempty"`

	// (String) The name of the federated graph to register the operations on.
	// The name of the federated graph to register the operations on.
	FederatedGraphName *string `json:"federatedGraphName,omitempty" tf:"federated_graph_name,omitempty"`

	// (String) The unique identifier of the client the operations are registered for.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) The namespace of the federated graph.
	// The namespace of the federated graph.
	Namespace *string `json:"namespace,omitempty" tf:"namespace,omitempty"`

	// (Map of String) The persisted operations as a map of an arbitrary label to the contents of a plain GraphQL document. JSON manifests are not supported yet.
	// The persisted operations as a map of an arbitrary label to the contents of a plain GraphQL document. JSON manifests are not supported yet.
	// +mapType=granular
	Operations map[string]*string `json:"operations,omitempty" tf:"operations,omitempty"`
}

type PersistedOperationsParameters struct {

	// (String) The name of the client the operations belong to (e.g. web, ios). The client is created on first publish.
	// The name of the client the operations belong to (e.g. `web`, `ios`). The client is created on first publish.
	// +kubebuilder:validation:Optional
	ClientName *string `json:"clientName,omitempty" tf:"client_name,omitempty"`

	// (String) The name of the federated graph to register the operations on.
	// The name of the federated graph to register the operations on.
	// +crossplane:generate:reference:type=github.com/web-seven/provider-wundergraph-cosmo/apis/namespaced/graph/v1alpha1.FederatedGraph
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("name",false)
	// +crossplane:generate:reference:refFieldName=FederatedGraphRef
	// +crossplane:generate:reference:selectorFieldName=FederatedGraphSelector
	// +kubebuilder:validation:Optional
	FederatedGraphName *string `json:"federatedGraphName,omitempty" tf:"federated_graph_name,omitempty"`

	// Reference to a FederatedGraph in graph to populate federatedGraphName.
	// +kubebuilder:validation:Optional
	FederatedGraphRef *v2.NamespacedReference `json:"federatedGraphRef,omitempty" tf:"-"`

	// Selector for a FederatedGraph in graph to populate federatedGraphName.
	// +kubebuilder:validation:Optional
	FederatedGraphSelector *v2.NamespacedSelector `json:"federatedGraphSelector,omitempty" tf:"-"`

	// (String) The namespace of the federated graph.
	// The namespace of the federated graph.
	// +crossplane:generate:reference:type=github.com/web-seven/provider-wundergraph-cosmo/apis/namespaced/graph/v1alpha1.CosmoNamespace
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("name",false)
	// +crossplane:generate:reference:refFieldName=NamespaceRef
	// +crossplane:generate:reference:selectorFieldName=NamespaceSelector
	// +kubebuilder:validation:Optional
	Namespace *string `json:"namespace,omitempty" tf:"namespace,omitempty"`

	// Reference to a CosmoNamespace in graph to populate namespace.
	// +kubebuilder:validation:Optional
	NamespaceRef *v2.NamespacedReference `json:"namespaceRef,omitempty" tf:"-"`

	// Selector for a CosmoNamespace in graph to populate namespace.
	// +kubebuilder:validation:Optional
	NamespaceSelector *v2.NamespacedSelector `json:"namespaceSelector,omitempty" tf:"-"`

	// (Map of String) The persisted operations as a map of an arbitrary label to the contents of a plain GraphQL document. JSON manifests are not supported yet.
	// The persisted operations as a map of an arbitrary label to the contents of a plain GraphQL document. JSON manifests are not supported yet.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Operations map[string]*string `json:"operations,omitempty" tf:"operations,omitempty"`
}

// PersistedOperationsSpec defines the desired state of PersistedOperations
type PersistedOperationsSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            PersistedOperationsParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider PersistedOperationsInitParameters `json:"initProvider,omitempty"`
}

// PersistedOperationsStatus defines the observed state of PersistedOperations.
type PersistedOperationsStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               PersistedOperationsObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// PersistedOperations is the Schema for the PersistedOperationss API. Manages the full set of persisted operations (safelisted GraphQL operations) registered for a client of a federated graph.g. via wgc operations push) to the same client will show up as drift and be removed on the next apply. Destroying the resource deletes the operations it manages but leaves the client record itself in place. Each operation value must be the raw contents of a plain GraphQL document. The JSON manifest formats accepted by wgc operations push (Apollo persisted query manifests, Relay query maps) are not supported yet and are rejected at plan time. Operations are content-addressed: their identifier is the hex-encoded SHA-256 hash of their contents, matching the behavior of wgc operations push. Publishing is not transactional: if an operation conflicts with an existing one (same id, different contents), the create or update fails but the non-conflicting operations remain registered; re-applying after fixing the conflict converges, since publishing is idempotent. Existing operations can be imported with the id format federated_graph_name:namespace:client_name. For more information on persisted operations, please refer to the Cosmo Documentation https://cosmo-docs.wundergraph.com/router/persisted-queries/persisted-operations.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,cosmo}
type PersistedOperations struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.clientName) || (has(self.initProvider) && has(self.initProvider.clientName))",message="spec.forProvider.clientName is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.operations) || (has(self.initProvider) && has(self.initProvider.operations))",message="spec.forProvider.operations is a required parameter"
	Spec   PersistedOperationsSpec   `json:"spec"`
	Status PersistedOperationsStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// PersistedOperationsList contains a list of PersistedOperationss
type PersistedOperationsList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []PersistedOperations `json:"items"`
}

// Repository type metadata.
var (
	PersistedOperations_Kind             = "PersistedOperations"
	PersistedOperations_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: PersistedOperations_Kind}.String()
	PersistedOperations_KindAPIVersion   = PersistedOperations_Kind + "." + CRDGroupVersion.String()
	PersistedOperations_GroupVersionKind = CRDGroupVersion.WithKind(PersistedOperations_Kind)
)

func init() {
	SchemeBuilder.Register(&PersistedOperations{}, &PersistedOperationsList{})
}
