// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type SubgraphInitParameters struct {

	// driven.
	// Indicates if the subgraph is event-driven.
	IsEventDrivenGraph *bool `json:"isEventDrivenGraph,omitempty" tf:"is_event_driven_graph,omitempty"`

	// (Map of String) Labels for the subgraph.
	// Labels for the subgraph.
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// (String) The name of the subgraph.
	// The name of the subgraph.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The namespace in which the subgraph is located.
	// The namespace in which the subgraph is located.
	// +crossplane:generate:reference:type=github.com/web-seven/provider-wundergraph-cosmo/apis/namespaced/graph/v1alpha1.CosmoNamespace
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("name",false)
	// +crossplane:generate:reference:refFieldName=NamespaceRef
	// +crossplane:generate:reference:selectorFieldName=NamespaceSelector
	Namespace *string `json:"namespace,omitempty" tf:"namespace,omitempty"`

	// Reference to a CosmoNamespace in graph to populate namespace.
	// +kubebuilder:validation:Optional
	NamespaceRef *v2.NamespacedReference `json:"namespaceRef,omitempty" tf:"-"`

	// Selector for a CosmoNamespace in graph to populate namespace.
	// +kubebuilder:validation:Optional
	NamespaceSelector *v2.NamespacedSelector `json:"namespaceSelector,omitempty" tf:"-"`

	// (String) The readme for the subgraph.
	// The readme for the subgraph.
	Readme *string `json:"readme,omitempty" tf:"readme,omitempty"`

	// (String) The routing URL of the subgraph. Routing URL is required for normal subgraphs but not for event driven subgraphs.
	// The routing URL of the subgraph. Routing URL is required for normal subgraphs but not for event driven subgraphs.
	RoutingURL *string `json:"routingUrl,omitempty" tf:"routing_url,omitempty"`

	// (String) The schema for the subgraph.
	// The schema for the subgraph.
	Schema *string `json:"schema,omitempty" tf:"schema,omitempty"`

	// (String) The subscription protocol for the subgraph.
	// The subscription protocol for the subgraph.
	SubscriptionProtocol *string `json:"subscriptionProtocol,omitempty" tf:"subscription_protocol,omitempty"`

	// (String) The subscription URL for the subgraph.
	// The subscription URL for the subgraph.
	SubscriptionURL *string `json:"subscriptionUrl,omitempty" tf:"subscription_url,omitempty"`

	// (Boolean) Unset labels for the subgraph.
	// Unset labels for the subgraph.
	UnsetLabels *bool `json:"unsetLabels,omitempty" tf:"unset_labels,omitempty"`

	// (String) The websocket subprotocol for the subgraph.
	// The websocket subprotocol for the subgraph.
	WebsocketSubprotocol *string `json:"websocketSubprotocol,omitempty" tf:"websocket_subprotocol,omitempty"`
}

type SubgraphObservation struct {

	// (String) The unique identifier of the subgraph resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// driven.
	// Indicates if the subgraph is event-driven.
	IsEventDrivenGraph *bool `json:"isEventDrivenGraph,omitempty" tf:"is_event_driven_graph,omitempty"`

	// (Map of String) Labels for the subgraph.
	// Labels for the subgraph.
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// (String) The name of the subgraph.
	// The name of the subgraph.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The namespace in which the subgraph is located.
	// The namespace in which the subgraph is located.
	Namespace *string `json:"namespace,omitempty" tf:"namespace,omitempty"`

	// (String) The readme for the subgraph.
	// The readme for the subgraph.
	Readme *string `json:"readme,omitempty" tf:"readme,omitempty"`

	// (String) The routing URL of the subgraph. Routing URL is required for normal subgraphs but not for event driven subgraphs.
	// The routing URL of the subgraph. Routing URL is required for normal subgraphs but not for event driven subgraphs.
	RoutingURL *string `json:"routingUrl,omitempty" tf:"routing_url,omitempty"`

	// (String) The schema for the subgraph.
	// The schema for the subgraph.
	Schema *string `json:"schema,omitempty" tf:"schema,omitempty"`

	// (String) The subscription protocol for the subgraph.
	// The subscription protocol for the subgraph.
	SubscriptionProtocol *string `json:"subscriptionProtocol,omitempty" tf:"subscription_protocol,omitempty"`

	// (String) The subscription URL for the subgraph.
	// The subscription URL for the subgraph.
	SubscriptionURL *string `json:"subscriptionUrl,omitempty" tf:"subscription_url,omitempty"`

	// (Boolean) Unset labels for the subgraph.
	// Unset labels for the subgraph.
	UnsetLabels *bool `json:"unsetLabels,omitempty" tf:"unset_labels,omitempty"`

	// (String) The websocket subprotocol for the subgraph.
	// The websocket subprotocol for the subgraph.
	WebsocketSubprotocol *string `json:"websocketSubprotocol,omitempty" tf:"websocket_subprotocol,omitempty"`
}

type SubgraphParameters struct {

	// driven.
	// Indicates if the subgraph is event-driven.
	// +kubebuilder:validation:Optional
	IsEventDrivenGraph *bool `json:"isEventDrivenGraph,omitempty" tf:"is_event_driven_graph,omitempty"`

	// (Map of String) Labels for the subgraph.
	// Labels for the subgraph.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// (String) The name of the subgraph.
	// The name of the subgraph.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The namespace in which the subgraph is located.
	// The namespace in which the subgraph is located.
	// +crossplane:generate:reference:type=github.com/web-seven/provider-wundergraph-cosmo/apis/namespaced/graph/v1alpha1.CosmoNamespace
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("name",false)
	// +crossplane:generate:reference:refFieldName=NamespaceRef
	// +crossplane:generate:reference:selectorFieldName=NamespaceSelector
	// +kubebuilder:validation:Optional
	Namespace *string `json:"namespace,omitempty" tf:"namespace,omitempty"`

	// Reference to a CosmoNamespace in graph to populate namespace.
	// +kubebuilder:validation:Optional
	NamespaceRef *v2.NamespacedReference `json:"namespaceRef,omitempty" tf:"-"`

	// Selector for a CosmoNamespace in graph to populate namespace.
	// +kubebuilder:validation:Optional
	NamespaceSelector *v2.NamespacedSelector `json:"namespaceSelector,omitempty" tf:"-"`

	// (String) The readme for the subgraph.
	// The readme for the subgraph.
	// +kubebuilder:validation:Optional
	Readme *string `json:"readme,omitempty" tf:"readme,omitempty"`

	// (String) The routing URL of the subgraph. Routing URL is required for normal subgraphs but not for event driven subgraphs.
	// The routing URL of the subgraph. Routing URL is required for normal subgraphs but not for event driven subgraphs.
	// +kubebuilder:validation:Optional
	RoutingURL *string `json:"routingUrl,omitempty" tf:"routing_url,omitempty"`

	// (String) The schema for the subgraph.
	// The schema for the subgraph.
	// +kubebuilder:validation:Optional
	Schema *string `json:"schema,omitempty" tf:"schema,omitempty"`

	// (String) The subscription protocol for the subgraph.
	// The subscription protocol for the subgraph.
	// +kubebuilder:validation:Optional
	SubscriptionProtocol *string `json:"subscriptionProtocol,omitempty" tf:"subscription_protocol,omitempty"`

	// (String) The subscription URL for the subgraph.
	// The subscription URL for the subgraph.
	// +kubebuilder:validation:Optional
	SubscriptionURL *string `json:"subscriptionUrl,omitempty" tf:"subscription_url,omitempty"`

	// (Boolean) Unset labels for the subgraph.
	// Unset labels for the subgraph.
	// +kubebuilder:validation:Optional
	UnsetLabels *bool `json:"unsetLabels,omitempty" tf:"unset_labels,omitempty"`

	// (String) The websocket subprotocol for the subgraph.
	// The websocket subprotocol for the subgraph.
	// +kubebuilder:validation:Optional
	WebsocketSubprotocol *string `json:"websocketSubprotocol,omitempty" tf:"websocket_subprotocol,omitempty"`
}

// SubgraphSpec defines the desired state of Subgraph
type SubgraphSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            SubgraphParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider SubgraphInitParameters `json:"initProvider,omitempty"`
}

// SubgraphStatus defines the observed state of Subgraph.
type SubgraphStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               SubgraphObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Subgraph is the Schema for the Subgraphs API. This resource handles subgraphs. Each subgraph is responsible for defining its specific segment of the schema and managing the related queries. For more information on subgraphs, please refer to the Cosmo Documentation https://cosmo-docs.wundergraph.com/cli/subgraph.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,cosmo}
type Subgraph struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   SubgraphSpec   `json:"spec"`
	Status SubgraphStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// SubgraphList contains a list of Subgraphs
type SubgraphList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Subgraph `json:"items"`
}

// Repository type metadata.
var (
	Subgraph_Kind             = "Subgraph"
	Subgraph_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Subgraph_Kind}.String()
	Subgraph_KindAPIVersion   = Subgraph_Kind + "." + CRDGroupVersion.String()
	Subgraph_GroupVersionKind = CRDGroupVersion.WithKind(Subgraph_Kind)
)

func init() {
	SchemeBuilder.Register(&Subgraph{}, &SubgraphList{})
}
