// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type ContractInitParameters struct {

	// (String)
	AdmissionWebhookSecretSecretRef *v2.SecretKeySelector `json:"admissionWebhookSecretSecretRef,omitempty" tf:"-"`

	// (String)
	AdmissionWebhookURL *string `json:"admissionWebhookUrl,omitempty" tf:"admission_webhook_url,omitempty"`

	// (List of String)
	ExcludeTags []*string `json:"excludeTags,omitempty" tf:"exclude_tags,omitempty"`

	// (List of String)
	IncludeTags []*string `json:"includeTags,omitempty" tf:"include_tags,omitempty"`

	// (String)
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String)
	// +crossplane:generate:reference:type=github.com/web-seven/provider-wundergraph-cosmo/apis/cluster/graph/v1alpha1.CosmoNamespace
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("name",false)
	// +crossplane:generate:reference:refFieldName=NamespaceRef
	// +crossplane:generate:reference:selectorFieldName=NamespaceSelector
	Namespace *string `json:"namespace,omitempty" tf:"namespace,omitempty"`

	// Reference to a CosmoNamespace in graph to populate namespace.
	// +kubebuilder:validation:Optional
	NamespaceRef *v2.Reference `json:"namespaceRef,omitempty" tf:"-"`

	// Selector for a CosmoNamespace in graph to populate namespace.
	// +kubebuilder:validation:Optional
	NamespaceSelector *v2.Selector `json:"namespaceSelector,omitempty" tf:"-"`

	// (String)
	Readme *string `json:"readme,omitempty" tf:"readme,omitempty"`

	// (String)
	RoutingURL *string `json:"routingUrl,omitempty" tf:"routing_url,omitempty"`

	// (String)
	// +crossplane:generate:reference:type=github.com/web-seven/provider-wundergraph-cosmo/apis/cluster/graph/v1alpha1.FederatedGraph
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("name",false)
	// +crossplane:generate:reference:refFieldName=SourceRef
	// +crossplane:generate:reference:selectorFieldName=SourceSelector
	Source *string `json:"source,omitempty" tf:"source,omitempty"`

	// Reference to a FederatedGraph in graph to populate source.
	// +kubebuilder:validation:Optional
	SourceRef *v2.Reference `json:"sourceRef,omitempty" tf:"-"`

	// Selector for a FederatedGraph in graph to populate source.
	// +kubebuilder:validation:Optional
	SourceSelector *v2.Selector `json:"sourceSelector,omitempty" tf:"-"`

	// (Boolean)
	SupportsFederation *bool `json:"supportsFederation,omitempty" tf:"supports_federation,omitempty"`
}

type ContractObservation struct {

	// (String)
	AdmissionWebhookURL *string `json:"admissionWebhookUrl,omitempty" tf:"admission_webhook_url,omitempty"`

	// (List of String)
	ExcludeTags []*string `json:"excludeTags,omitempty" tf:"exclude_tags,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (List of String)
	IncludeTags []*string `json:"includeTags,omitempty" tf:"include_tags,omitempty"`

	// (String)
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String)
	Namespace *string `json:"namespace,omitempty" tf:"namespace,omitempty"`

	// (String)
	Readme *string `json:"readme,omitempty" tf:"readme,omitempty"`

	// (String)
	RoutingURL *string `json:"routingUrl,omitempty" tf:"routing_url,omitempty"`

	// (String)
	Source *string `json:"source,omitempty" tf:"source,omitempty"`

	// (Boolean)
	SupportsFederation *bool `json:"supportsFederation,omitempty" tf:"supports_federation,omitempty"`
}

type ContractParameters struct {

	// (String)
	// +kubebuilder:validation:Optional
	AdmissionWebhookSecretSecretRef *v2.SecretKeySelector `json:"admissionWebhookSecretSecretRef,omitempty" tf:"-"`

	// (String)
	// +kubebuilder:validation:Optional
	AdmissionWebhookURL *string `json:"admissionWebhookUrl,omitempty" tf:"admission_webhook_url,omitempty"`

	// (List of String)
	// +kubebuilder:validation:Optional
	ExcludeTags []*string `json:"excludeTags,omitempty" tf:"exclude_tags,omitempty"`

	// (List of String)
	// +kubebuilder:validation:Optional
	IncludeTags []*string `json:"includeTags,omitempty" tf:"include_tags,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String)
	// +crossplane:generate:reference:type=github.com/web-seven/provider-wundergraph-cosmo/apis/cluster/graph/v1alpha1.CosmoNamespace
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("name",false)
	// +crossplane:generate:reference:refFieldName=NamespaceRef
	// +crossplane:generate:reference:selectorFieldName=NamespaceSelector
	// +kubebuilder:validation:Optional
	Namespace *string `json:"namespace,omitempty" tf:"namespace,omitempty"`

	// Reference to a CosmoNamespace in graph to populate namespace.
	// +kubebuilder:validation:Optional
	NamespaceRef *v2.Reference `json:"namespaceRef,omitempty" tf:"-"`

	// Selector for a CosmoNamespace in graph to populate namespace.
	// +kubebuilder:validation:Optional
	NamespaceSelector *v2.Selector `json:"namespaceSelector,omitempty" tf:"-"`

	// (String)
	// +kubebuilder:validation:Optional
	Readme *string `json:"readme,omitempty" tf:"readme,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	RoutingURL *string `json:"routingUrl,omitempty" tf:"routing_url,omitempty"`

	// (String)
	// +crossplane:generate:reference:type=github.com/web-seven/provider-wundergraph-cosmo/apis/cluster/graph/v1alpha1.FederatedGraph
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("name",false)
	// +crossplane:generate:reference:refFieldName=SourceRef
	// +crossplane:generate:reference:selectorFieldName=SourceSelector
	// +kubebuilder:validation:Optional
	Source *string `json:"source,omitempty" tf:"source,omitempty"`

	// Reference to a FederatedGraph in graph to populate source.
	// +kubebuilder:validation:Optional
	SourceRef *v2.Reference `json:"sourceRef,omitempty" tf:"-"`

	// Selector for a FederatedGraph in graph to populate source.
	// +kubebuilder:validation:Optional
	SourceSelector *v2.Selector `json:"sourceSelector,omitempty" tf:"-"`

	// (Boolean)
	// +kubebuilder:validation:Optional
	SupportsFederation *bool `json:"supportsFederation,omitempty" tf:"supports_federation,omitempty"`
}

// ContractSpec defines the desired state of Contract
type ContractSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   ContractParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ContractInitParameters `json:"initProvider,omitempty"`
}

// ContractStatus defines the observed state of Contract.
type ContractStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               ContractObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Contract is the Schema for the Contracts API.  For more information, refer to the Cosmo Documentation at https://cosmo-docs.wundergraph.com/concepts/schema-contracts.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,cosmo}
type Contract struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.routingUrl) || (has(self.initProvider) && has(self.initProvider.routingUrl))",message="spec.forProvider.routingUrl is a required parameter"
	Spec   ContractSpec   `json:"spec"`
	Status ContractStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ContractList contains a list of Contracts
type ContractList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Contract `json:"items"`
}

// Repository type metadata.
var (
	Contract_Kind             = "Contract"
	Contract_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Contract_Kind}.String()
	Contract_KindAPIVersion   = Contract_Kind + "." + CRDGroupVersion.String()
	Contract_GroupVersionKind = CRDGroupVersion.WithKind(Contract_Kind)
)

func init() {
	SchemeBuilder.Register(&Contract{}, &ContractList{})
}
