// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type FederatedGraphInitParameters struct {

	// (String, Sensitive) The secret token used to authenticate the admission webhook requests.
	// The secret token used to authenticate the admission webhook requests.
	AdmissionWebhookSecretSecretRef *v2.SecretKeySelector `json:"admissionWebhookSecretSecretRef,omitempty" tf:"-"`

	// (String) The URL for the admission webhook that will be triggered during graph operations.
	// The URL for the admission webhook that will be triggered during graph operations.
	AdmissionWebhookURL *string `json:"admissionWebhookUrl,omitempty" tf:"admission_webhook_url,omitempty"`

	// (List of String) A list of label matchers used to select the services that will form the federated graph.
	// A list of label matchers used to select the services that will form the federated graph.
	LabelMatchers []*string `json:"labelMatchers,omitempty" tf:"label_matchers,omitempty"`

	// (String) The name of the federated graph. This is used to identify the graph and must be unique within the namespace.
	// The name of the federated graph. This is used to identify the graph and must be unique within the namespace.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The namespace in which the federated graph is located. Defaults to 'default' if not provided.
	// The namespace in which the federated graph is located. Defaults to 'default' if not provided.
	// +crossplane:generate:reference:type=github.com/web-seven/provider-wundergraph-cosmo/apis/cluster/graph/v1alpha1.CosmoNamespace
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("name",false)
	// +crossplane:generate:reference:refFieldName=NamespaceRef
	// +crossplane:generate:reference:selectorFieldName=NamespaceSelector
	Namespace *string `json:"namespace,omitempty" tf:"namespace,omitempty"`

	// Reference to a CosmoNamespace in graph to populate namespace.
	// +kubebuilder:validation:Optional
	NamespaceRef *v2.Reference `json:"namespaceRef,omitempty" tf:"-"`

	// Selector for a CosmoNamespace in graph to populate namespace.
	// +kubebuilder:validation:Optional
	NamespaceSelector *v2.Selector `json:"namespaceSelector,omitempty" tf:"-"`

	// (String) Readme content for the federated graph.
	// Readme content for the federated graph.
	Readme *string `json:"readme,omitempty" tf:"readme,omitempty"`

	// (String) The URL of the service that routes requests to the federated graph.
	// The URL of the service that routes requests to the federated graph.
	RoutingURL *string `json:"routingUrl,omitempty" tf:"routing_url,omitempty"`
}

type FederatedGraphObservation struct {

	// (String) The URL for the admission webhook that will be triggered during graph operations.
	// The URL for the admission webhook that will be triggered during graph operations.
	AdmissionWebhookURL *string `json:"admissionWebhookUrl,omitempty" tf:"admission_webhook_url,omitempty"`

	// (String) The unique identifier of the federated graph resource, automatically generated by the system.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (List of String) A list of label matchers used to select the services that will form the federated graph.
	// A list of label matchers used to select the services that will form the federated graph.
	LabelMatchers []*string `json:"labelMatchers,omitempty" tf:"label_matchers,omitempty"`

	// (String) The name of the federated graph. This is used to identify the graph and must be unique within the namespace.
	// The name of the federated graph. This is used to identify the graph and must be unique within the namespace.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The namespace in which the federated graph is located. Defaults to 'default' if not provided.
	// The namespace in which the federated graph is located. Defaults to 'default' if not provided.
	Namespace *string `json:"namespace,omitempty" tf:"namespace,omitempty"`

	// (String) Readme content for the federated graph.
	// Readme content for the federated graph.
	Readme *string `json:"readme,omitempty" tf:"readme,omitempty"`

	// (String) The URL of the service that routes requests to the federated graph.
	// The URL of the service that routes requests to the federated graph.
	RoutingURL *string `json:"routingUrl,omitempty" tf:"routing_url,omitempty"`
}

type FederatedGraphParameters struct {

	// (String, Sensitive) The secret token used to authenticate the admission webhook requests.
	// The secret token used to authenticate the admission webhook requests.
	// +kubebuilder:validation:Optional
	AdmissionWebhookSecretSecretRef *v2.SecretKeySelector `json:"admissionWebhookSecretSecretRef,omitempty" tf:"-"`

	// (String) The URL for the admission webhook that will be triggered during graph operations.
	// The URL for the admission webhook that will be triggered during graph operations.
	// +kubebuilder:validation:Optional
	AdmissionWebhookURL *string `json:"admissionWebhookUrl,omitempty" tf:"admission_webhook_url,omitempty"`

	// (List of String) A list of label matchers used to select the services that will form the federated graph.
	// A list of label matchers used to select the services that will form the federated graph.
	// +kubebuilder:validation:Optional
	LabelMatchers []*string `json:"labelMatchers,omitempty" tf:"label_matchers,omitempty"`

	// (String) The name of the federated graph. This is used to identify the graph and must be unique within the namespace.
	// The name of the federated graph. This is used to identify the graph and must be unique within the namespace.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The namespace in which the federated graph is located. Defaults to 'default' if not provided.
	// The namespace in which the federated graph is located. Defaults to 'default' if not provided.
	// +crossplane:generate:reference:type=github.com/web-seven/provider-wundergraph-cosmo/apis/cluster/graph/v1alpha1.CosmoNamespace
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("name",false)
	// +crossplane:generate:reference:refFieldName=NamespaceRef
	// +crossplane:generate:reference:selectorFieldName=NamespaceSelector
	// +kubebuilder:validation:Optional
	Namespace *string `json:"namespace,omitempty" tf:"namespace,omitempty"`

	// Reference to a CosmoNamespace in graph to populate namespace.
	// +kubebuilder:validation:Optional
	NamespaceRef *v2.Reference `json:"namespaceRef,omitempty" tf:"-"`

	// Selector for a CosmoNamespace in graph to populate namespace.
	// +kubebuilder:validation:Optional
	NamespaceSelector *v2.Selector `json:"namespaceSelector,omitempty" tf:"-"`

	// (String) Readme content for the federated graph.
	// Readme content for the federated graph.
	// +kubebuilder:validation:Optional
	Readme *string `json:"readme,omitempty" tf:"readme,omitempty"`

	// (String) The URL of the service that routes requests to the federated graph.
	// The URL of the service that routes requests to the federated graph.
	// +kubebuilder:validation:Optional
	RoutingURL *string `json:"routingUrl,omitempty" tf:"routing_url,omitempty"`
}

// FederatedGraphSpec defines the desired state of FederatedGraph
type FederatedGraphSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   FederatedGraphParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider FederatedGraphInitParameters `json:"initProvider,omitempty"`
}

// FederatedGraphStatus defines the observed state of FederatedGraph.
type FederatedGraphStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               FederatedGraphObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// FederatedGraph is the Schema for the FederatedGraphs API. The federated graph resource is used to manage a single, unified data graph that is composed of multiple subgraphs. For more information on federated graphs, please refer to the Cosmo Documentation https://cosmo-docs.wundergraph.com/cli/federated-graph.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,cosmo}
type FederatedGraph struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.routingUrl) || (has(self.initProvider) && has(self.initProvider.routingUrl))",message="spec.forProvider.routingUrl is a required parameter"
	Spec   FederatedGraphSpec   `json:"spec"`
	Status FederatedGraphStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// FederatedGraphList contains a list of FederatedGraphs
type FederatedGraphList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []FederatedGraph `json:"items"`
}

// Repository type metadata.
var (
	FederatedGraph_Kind             = "FederatedGraph"
	FederatedGraph_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: FederatedGraph_Kind}.String()
	FederatedGraph_KindAPIVersion   = FederatedGraph_Kind + "." + CRDGroupVersion.String()
	FederatedGraph_GroupVersionKind = CRDGroupVersion.WithKind(FederatedGraph_Kind)
)

func init() {
	SchemeBuilder.Register(&FederatedGraph{}, &FederatedGraphList{})
}
