// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type FeatureSubgraphInitParameters struct {

	// (String) The name of the base subgraph that this feature subgraph extends.
	// The name of the base subgraph that this feature subgraph extends.
	// +crossplane:generate:reference:type=github.com/web-seven/provider-wundergraph-cosmo/apis/cluster/graph/v1alpha1.Subgraph
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("name",false)
	// +crossplane:generate:reference:refFieldName=BaseSubgraphRef
	// +crossplane:generate:reference:selectorFieldName=BaseSubgraphSelector
	BaseSubgraphName *string `json:"baseSubgraphName,omitempty" tf:"base_subgraph_name,omitempty"`

	// Reference to a Subgraph in graph to populate baseSubgraphName.
	// +kubebuilder:validation:Optional
	BaseSubgraphRef *v2.Reference `json:"baseSubgraphRef,omitempty" tf:"-"`

	// Selector for a Subgraph in graph to populate baseSubgraphName.
	// +kubebuilder:validation:Optional
	BaseSubgraphSelector *v2.Selector `json:"baseSubgraphSelector,omitempty" tf:"-"`

	// (String) The name of the feature subgraph.
	// The name of the feature subgraph.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The namespace to create the feature subgraph in.
	// The namespace to create the feature subgraph in.
	// +crossplane:generate:reference:type=github.com/web-seven/provider-wundergraph-cosmo/apis/cluster/graph/v1alpha1.CosmoNamespace
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("name",false)
	// +crossplane:generate:reference:refFieldName=NamespaceRef
	// +crossplane:generate:reference:selectorFieldName=NamespaceSelector
	Namespace *string `json:"namespace,omitempty" tf:"namespace,omitempty"`

	// Reference to a CosmoNamespace in graph to populate namespace.
	// +kubebuilder:validation:Optional
	NamespaceRef *v2.Reference `json:"namespaceRef,omitempty" tf:"-"`

	// Selector for a CosmoNamespace in graph to populate namespace.
	// +kubebuilder:validation:Optional
	NamespaceSelector *v2.Selector `json:"namespaceSelector,omitempty" tf:"-"`

	// (String) The readme for the subgraph.
	// The readme for the subgraph.
	Readme *string `json:"readme,omitempty" tf:"readme,omitempty"`

	// (String) The routing URL of the feature subgraph.
	// The routing URL of the feature subgraph.
	RoutingURL *string `json:"routingUrl,omitempty" tf:"routing_url,omitempty"`

	// (String) The schema for the subgraph.
	// The schema for the subgraph.
	Schema *string `json:"schema,omitempty" tf:"schema,omitempty"`

	// (String) The subscription protocol for the subgraph.
	// The subscription protocol for the subgraph.
	SubscriptionProtocol *string `json:"subscriptionProtocol,omitempty" tf:"subscription_protocol,omitempty"`

	// (String) The subscription URL for the subgraph.
	// The subscription URL for the subgraph.
	SubscriptionURL *string `json:"subscriptionUrl,omitempty" tf:"subscription_url,omitempty"`

	// (String) The websocket subprotocol for the subgraph.
	// The websocket subprotocol for the subgraph.
	WebsocketSubprotocol *string `json:"websocketSubprotocol,omitempty" tf:"websocket_subprotocol,omitempty"`
}

type FeatureSubgraphObservation struct {

	// (String) The name of the base subgraph that this feature subgraph extends.
	// The name of the base subgraph that this feature subgraph extends.
	BaseSubgraphName *string `json:"baseSubgraphName,omitempty" tf:"base_subgraph_name,omitempty"`

	// (String) The unique identifier of the feature subgraph.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) The name of the feature subgraph.
	// The name of the feature subgraph.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The namespace to create the feature subgraph in.
	// The namespace to create the feature subgraph in.
	Namespace *string `json:"namespace,omitempty" tf:"namespace,omitempty"`

	// (String) The readme for the subgraph.
	// The readme for the subgraph.
	Readme *string `json:"readme,omitempty" tf:"readme,omitempty"`

	// (String) The routing URL of the feature subgraph.
	// The routing URL of the feature subgraph.
	RoutingURL *string `json:"routingUrl,omitempty" tf:"routing_url,omitempty"`

	// (String) The schema for the subgraph.
	// The schema for the subgraph.
	Schema *string `json:"schema,omitempty" tf:"schema,omitempty"`

	// (String) The subscription protocol for the subgraph.
	// The subscription protocol for the subgraph.
	SubscriptionProtocol *string `json:"subscriptionProtocol,omitempty" tf:"subscription_protocol,omitempty"`

	// (String) The subscription URL for the subgraph.
	// The subscription URL for the subgraph.
	SubscriptionURL *string `json:"subscriptionUrl,omitempty" tf:"subscription_url,omitempty"`

	// (String) The websocket subprotocol for the subgraph.
	// The websocket subprotocol for the subgraph.
	WebsocketSubprotocol *string `json:"websocketSubprotocol,omitempty" tf:"websocket_subprotocol,omitempty"`
}

type FeatureSubgraphParameters struct {

	// (String) The name of the base subgraph that this feature subgraph extends.
	// The name of the base subgraph that this feature subgraph extends.
	// +crossplane:generate:reference:type=github.com/web-seven/provider-wundergraph-cosmo/apis/cluster/graph/v1alpha1.Subgraph
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("name",false)
	// +crossplane:generate:reference:refFieldName=BaseSubgraphRef
	// +crossplane:generate:reference:selectorFieldName=BaseSubgraphSelector
	// +kubebuilder:validation:Optional
	BaseSubgraphName *string `json:"baseSubgraphName,omitempty" tf:"base_subgraph_name,omitempty"`

	// Reference to a Subgraph in graph to populate baseSubgraphName.
	// +kubebuilder:validation:Optional
	BaseSubgraphRef *v2.Reference `json:"baseSubgraphRef,omitempty" tf:"-"`

	// Selector for a Subgraph in graph to populate baseSubgraphName.
	// +kubebuilder:validation:Optional
	BaseSubgraphSelector *v2.Selector `json:"baseSubgraphSelector,omitempty" tf:"-"`

	// (String) The name of the feature subgraph.
	// The name of the feature subgraph.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The namespace to create the feature subgraph in.
	// The namespace to create the feature subgraph in.
	// +crossplane:generate:reference:type=github.com/web-seven/provider-wundergraph-cosmo/apis/cluster/graph/v1alpha1.CosmoNamespace
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("name",false)
	// +crossplane:generate:reference:refFieldName=NamespaceRef
	// +crossplane:generate:reference:selectorFieldName=NamespaceSelector
	// +kubebuilder:validation:Optional
	Namespace *string `json:"namespace,omitempty" tf:"namespace,omitempty"`

	// Reference to a CosmoNamespace in graph to populate namespace.
	// +kubebuilder:validation:Optional
	NamespaceRef *v2.Reference `json:"namespaceRef,omitempty" tf:"-"`

	// Selector for a CosmoNamespace in graph to populate namespace.
	// +kubebuilder:validation:Optional
	NamespaceSelector *v2.Selector `json:"namespaceSelector,omitempty" tf:"-"`

	// (String) The readme for the subgraph.
	// The readme for the subgraph.
	// +kubebuilder:validation:Optional
	Readme *string `json:"readme,omitempty" tf:"readme,omitempty"`

	// (String) The routing URL of the feature subgraph.
	// The routing URL of the feature subgraph.
	// +kubebuilder:validation:Optional
	RoutingURL *string `json:"routingUrl,omitempty" tf:"routing_url,omitempty"`

	// (String) The schema for the subgraph.
	// The schema for the subgraph.
	// +kubebuilder:validation:Optional
	Schema *string `json:"schema,omitempty" tf:"schema,omitempty"`

	// (String) The subscription protocol for the subgraph.
	// The subscription protocol for the subgraph.
	// +kubebuilder:validation:Optional
	SubscriptionProtocol *string `json:"subscriptionProtocol,omitempty" tf:"subscription_protocol,omitempty"`

	// (String) The subscription URL for the subgraph.
	// The subscription URL for the subgraph.
	// +kubebuilder:validation:Optional
	SubscriptionURL *string `json:"subscriptionUrl,omitempty" tf:"subscription_url,omitempty"`

	// (String) The websocket subprotocol for the subgraph.
	// The websocket subprotocol for the subgraph.
	// +kubebuilder:validation:Optional
	WebsocketSubprotocol *string `json:"websocketSubprotocol,omitempty" tf:"websocket_subprotocol,omitempty"`
}

// FeatureSubgraphSpec defines the desired state of FeatureSubgraph
type FeatureSubgraphSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   FeatureSubgraphParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider FeatureSubgraphInitParameters `json:"initProvider,omitempty"`
}

// FeatureSubgraphStatus defines the observed state of FeatureSubgraph.
type FeatureSubgraphStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               FeatureSubgraphObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// FeatureSubgraph is the Schema for the FeatureSubgraphs API. This resource handles feature subgraphs. Feature subgraphs are a special type of subgraph that can be used to extend the functionality of the platform. They require a base subgraph to be specified and can be used to add additional functionality to the base subgraph based on a specialized schema, that is published to this subgraph. For more information on feature subgraphs, please refer to the Cosmo Documentation https://cosmo-docs.wundergraph.com/cli/feature-subgraph.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,cosmo}
type FeatureSubgraph struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.routingUrl) || (has(self.initProvider) && has(self.initProvider.routingUrl))",message="spec.forProvider.routingUrl is a required parameter"
	Spec   FeatureSubgraphSpec   `json:"spec"`
	Status FeatureSubgraphStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// FeatureSubgraphList contains a list of FeatureSubgraphs
type FeatureSubgraphList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []FeatureSubgraph `json:"items"`
}

// Repository type metadata.
var (
	FeatureSubgraph_Kind             = "FeatureSubgraph"
	FeatureSubgraph_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: FeatureSubgraph_Kind}.String()
	FeatureSubgraph_KindAPIVersion   = FeatureSubgraph_Kind + "." + CRDGroupVersion.String()
	FeatureSubgraph_GroupVersionKind = CRDGroupVersion.WithKind(FeatureSubgraph_Kind)
)

func init() {
	SchemeBuilder.Register(&FeatureSubgraph{}, &FeatureSubgraphList{})
}
