// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type FeatureFlagInitParameters struct {

	// (Set of String) The list of feature subgraphs associated with the feature flag.
	// At least one feature subgraph must be provided.
	// The list of feature subgraphs associated with the feature flag.
	// At least one feature subgraph must be provided.
	// +crossplane:generate:reference:type=github.com/web-seven/provider-wundergraph-cosmo/apis/cluster/graph/v1alpha1.FeatureSubgraph
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("name",false)
	// +listType=set
	FeatureSubgraphs []*string `json:"featureSubgraphs,omitempty" tf:"feature_subgraphs,omitempty"`

	// References to FeatureSubgraph in graph to populate featureSubgraphs.
	// +kubebuilder:validation:Optional
	FeatureSubgraphsRefs []v2.Reference `json:"featureSubgraphsRefs,omitempty" tf:"-"`

	// Selector for a list of FeatureSubgraph in graph to populate featureSubgraphs.
	// +kubebuilder:validation:Optional
	FeatureSubgraphsSelector *v2.Selector `json:"featureSubgraphsSelector,omitempty" tf:"-"`

	// (Boolean) Indicates whether the feature flag is enabled.
	// Indicates whether the feature flag is enabled.
	IsEnabled *bool `json:"isEnabled,omitempty" tf:"is_enabled,omitempty"`

	// (Map of String) The labels associated with the feature flag. These labels indicate which
	// federated graphs can be associated with the feature flag to enabled calls against the corresponding feature subgraph.
	// The labels associated with the feature flag. These labels indicate which
	// federated graphs can be associated with the feature flag to enabled calls against the corresponding feature subgraph.
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// (String) The name of the feature flag.
	// The name of the feature flag.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The namespace of the feature flag.
	// The namespace of the feature flag.
	// +crossplane:generate:reference:type=github.com/web-seven/provider-wundergraph-cosmo/apis/cluster/graph/v1alpha1.CosmoNamespace
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("name",false)
	// +crossplane:generate:reference:refFieldName=NamespaceRef
	// +crossplane:generate:reference:selectorFieldName=NamespaceSelector
	Namespace *string `json:"namespace,omitempty" tf:"namespace,omitempty"`

	// Reference to a CosmoNamespace in graph to populate namespace.
	// +kubebuilder:validation:Optional
	NamespaceRef *v2.Reference `json:"namespaceRef,omitempty" tf:"-"`

	// Selector for a CosmoNamespace in graph to populate namespace.
	// +kubebuilder:validation:Optional
	NamespaceSelector *v2.Selector `json:"namespaceSelector,omitempty" tf:"-"`
}

type FeatureFlagObservation struct {

	// (String) The timestamp when the feature flag was created.
	// The timestamp when the feature flag was created.
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// (String) The user who created the feature flag.
	// The user who created the feature flag.
	CreatedBy *string `json:"createdBy,omitempty" tf:"created_by,omitempty"`

	// (Set of String) The list of feature subgraphs associated with the feature flag.
	// At least one feature subgraph must be provided.
	// The list of feature subgraphs associated with the feature flag.
	// At least one feature subgraph must be provided.
	// +listType=set
	FeatureSubgraphs []*string `json:"featureSubgraphs,omitempty" tf:"feature_subgraphs,omitempty"`

	// (String) The unique identifier of the feature flag.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Boolean) Indicates whether the feature flag is enabled.
	// Indicates whether the feature flag is enabled.
	IsEnabled *bool `json:"isEnabled,omitempty" tf:"is_enabled,omitempty"`

	// (Map of String) The labels associated with the feature flag. These labels indicate which
	// federated graphs can be associated with the feature flag to enabled calls against the corresponding feature subgraph.
	// The labels associated with the feature flag. These labels indicate which
	// federated graphs can be associated with the feature flag to enabled calls against the corresponding feature subgraph.
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// (String) The name of the feature flag.
	// The name of the feature flag.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The namespace of the feature flag.
	// The namespace of the feature flag.
	Namespace *string `json:"namespace,omitempty" tf:"namespace,omitempty"`

	// (String) The timestamp when the feature flag was last updated.
	// The timestamp when the feature flag was last updated.
	UpdatedAt *string `json:"updatedAt,omitempty" tf:"updated_at,omitempty"`
}

type FeatureFlagParameters struct {

	// (Set of String) The list of feature subgraphs associated with the feature flag.
	// At least one feature subgraph must be provided.
	// The list of feature subgraphs associated with the feature flag.
	// At least one feature subgraph must be provided.
	// +crossplane:generate:reference:type=github.com/web-seven/provider-wundergraph-cosmo/apis/cluster/graph/v1alpha1.FeatureSubgraph
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("name",false)
	// +kubebuilder:validation:Optional
	// +listType=set
	FeatureSubgraphs []*string `json:"featureSubgraphs,omitempty" tf:"feature_subgraphs,omitempty"`

	// References to FeatureSubgraph in graph to populate featureSubgraphs.
	// +kubebuilder:validation:Optional
	FeatureSubgraphsRefs []v2.Reference `json:"featureSubgraphsRefs,omitempty" tf:"-"`

	// Selector for a list of FeatureSubgraph in graph to populate featureSubgraphs.
	// +kubebuilder:validation:Optional
	FeatureSubgraphsSelector *v2.Selector `json:"featureSubgraphsSelector,omitempty" tf:"-"`

	// (Boolean) Indicates whether the feature flag is enabled.
	// Indicates whether the feature flag is enabled.
	// +kubebuilder:validation:Optional
	IsEnabled *bool `json:"isEnabled,omitempty" tf:"is_enabled,omitempty"`

	// (Map of String) The labels associated with the feature flag. These labels indicate which
	// federated graphs can be associated with the feature flag to enabled calls against the corresponding feature subgraph.
	// The labels associated with the feature flag. These labels indicate which
	// federated graphs can be associated with the feature flag to enabled calls against the corresponding feature subgraph.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// (String) The name of the feature flag.
	// The name of the feature flag.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The namespace of the feature flag.
	// The namespace of the feature flag.
	// +crossplane:generate:reference:type=github.com/web-seven/provider-wundergraph-cosmo/apis/cluster/graph/v1alpha1.CosmoNamespace
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("name",false)
	// +crossplane:generate:reference:refFieldName=NamespaceRef
	// +crossplane:generate:reference:selectorFieldName=NamespaceSelector
	// +kubebuilder:validation:Optional
	Namespace *string `json:"namespace,omitempty" tf:"namespace,omitempty"`

	// Reference to a CosmoNamespace in graph to populate namespace.
	// +kubebuilder:validation:Optional
	NamespaceRef *v2.Reference `json:"namespaceRef,omitempty" tf:"-"`

	// Selector for a CosmoNamespace in graph to populate namespace.
	// +kubebuilder:validation:Optional
	NamespaceSelector *v2.Selector `json:"namespaceSelector,omitempty" tf:"-"`
}

// FeatureFlagSpec defines the desired state of FeatureFlag
type FeatureFlagSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   FeatureFlagParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider FeatureFlagInitParameters `json:"initProvider,omitempty"`
}

// FeatureFlagStatus defines the observed state of FeatureFlag.
type FeatureFlagStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               FeatureFlagObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// FeatureFlag is the Schema for the FeatureFlags API. A feature flag is a group of one or more feature subgraphs. Each feature subgraph represents a replacement of a specific base subgraph that composes a federated graph. Feature flags define labels that dictate the federated graphs to which they will apply when enabled. Setting the corresponding feature-flag header or cookie value allows different graph constellations to be served to clients. For more information on feature flags, please refer to the Cosmo Documentation https://cosmo-docs.wundergraph.com/cli/feature-flags. To learn more about the concept of feature flags, please refer to the concept https://cosmo-docs.wundergraph.com/concepts/feature-flags.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,cosmo}
type FeatureFlag struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   FeatureFlagSpec   `json:"spec"`
	Status FeatureFlagStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// FeatureFlagList contains a list of FeatureFlags
type FeatureFlagList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []FeatureFlag `json:"items"`
}

// Repository type metadata.
var (
	FeatureFlag_Kind             = "FeatureFlag"
	FeatureFlag_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: FeatureFlag_Kind}.String()
	FeatureFlag_KindAPIVersion   = FeatureFlag_Kind + "." + CRDGroupVersion.String()
	FeatureFlag_GroupVersionKind = CRDGroupVersion.WithKind(FeatureFlag_Kind)
)

func init() {
	SchemeBuilder.Register(&FeatureFlag{}, &FeatureFlagList{})
}
