// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	reference "github.com/crossplane/crossplane-runtime/v2/pkg/reference"
	resource "github.com/crossplane/upjet/v2/pkg/resource"
	errors "github.com/pkg/errors"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this Contract.
func (mg *Contract) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Namespace),
		Extract:      resource.ExtractParamPath("name", false),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.NamespaceRef,
		Selector:     mg.Spec.ForProvider.NamespaceSelector,
		To: reference.To{
			List:    &CosmoNamespaceList{},
			Managed: &CosmoNamespace{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.Namespace")
	}
	mg.Spec.ForProvider.Namespace = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.NamespaceRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Source),
		Extract:      resource.ExtractParamPath("name", false),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.SourceRef,
		Selector:     mg.Spec.ForProvider.SourceSelector,
		To: reference.To{
			List:    &FederatedGraphList{},
			Managed: &FederatedGraph{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.Source")
	}
	mg.Spec.ForProvider.Source = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.SourceRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Namespace),
		Extract:      resource.ExtractParamPath("name", false),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.NamespaceRef,
		Selector:     mg.Spec.InitProvider.NamespaceSelector,
		To: reference.To{
			List:    &CosmoNamespaceList{},
			Managed: &CosmoNamespace{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.Namespace")
	}
	mg.Spec.InitProvider.Namespace = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.NamespaceRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Source),
		Extract:      resource.ExtractParamPath("name", false),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.SourceRef,
		Selector:     mg.Spec.InitProvider.SourceSelector,
		To: reference.To{
			List:    &FederatedGraphList{},
			Managed: &FederatedGraph{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.Source")
	}
	mg.Spec.InitProvider.Source = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.SourceRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this FeatureFlag.
func (mg *FeatureFlag) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var mrsp reference.MultiResolutionResponse
	var err error

	mrsp, err = r.ResolveMultiple(ctx, reference.MultiResolutionRequest{
		CurrentValues: reference.FromPtrValues(mg.Spec.ForProvider.FeatureSubgraphs),
		Extract:       resource.ExtractParamPath("name", false),
		Namespace:     mg.GetNamespace(),
		References:    mg.Spec.ForProvider.FeatureSubgraphsRefs,
		Selector:      mg.Spec.ForProvider.FeatureSubgraphsSelector,
		To: reference.To{
			List:    &FeatureSubgraphList{},
			Managed: &FeatureSubgraph{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.FeatureSubgraphs")
	}
	mg.Spec.ForProvider.FeatureSubgraphs = reference.ToPtrValues(mrsp.ResolvedValues)
	mg.Spec.ForProvider.FeatureSubgraphsRefs = mrsp.ResolvedReferences

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Namespace),
		Extract:      resource.ExtractParamPath("name", false),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.NamespaceRef,
		Selector:     mg.Spec.ForProvider.NamespaceSelector,
		To: reference.To{
			List:    &CosmoNamespaceList{},
			Managed: &CosmoNamespace{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.Namespace")
	}
	mg.Spec.ForProvider.Namespace = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.NamespaceRef = rsp.ResolvedReference

	mrsp, err = r.ResolveMultiple(ctx, reference.MultiResolutionRequest{
		CurrentValues: reference.FromPtrValues(mg.Spec.InitProvider.FeatureSubgraphs),
		Extract:       resource.ExtractParamPath("name", false),
		Namespace:     mg.GetNamespace(),
		References:    mg.Spec.InitProvider.FeatureSubgraphsRefs,
		Selector:      mg.Spec.InitProvider.FeatureSubgraphsSelector,
		To: reference.To{
			List:    &FeatureSubgraphList{},
			Managed: &FeatureSubgraph{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.FeatureSubgraphs")
	}
	mg.Spec.InitProvider.FeatureSubgraphs = reference.ToPtrValues(mrsp.ResolvedValues)
	mg.Spec.InitProvider.FeatureSubgraphsRefs = mrsp.ResolvedReferences

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Namespace),
		Extract:      resource.ExtractParamPath("name", false),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.NamespaceRef,
		Selector:     mg.Spec.InitProvider.NamespaceSelector,
		To: reference.To{
			List:    &CosmoNamespaceList{},
			Managed: &CosmoNamespace{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.Namespace")
	}
	mg.Spec.InitProvider.Namespace = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.NamespaceRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this FeatureSubgraph.
func (mg *FeatureSubgraph) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.BaseSubgraphName),
		Extract:      resource.ExtractParamPath("name", false),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.BaseSubgraphRef,
		Selector:     mg.Spec.ForProvider.BaseSubgraphSelector,
		To: reference.To{
			List:    &SubgraphList{},
			Managed: &Subgraph{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.BaseSubgraphName")
	}
	mg.Spec.ForProvider.BaseSubgraphName = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.BaseSubgraphRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Namespace),
		Extract:      resource.ExtractParamPath("name", false),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.NamespaceRef,
		Selector:     mg.Spec.ForProvider.NamespaceSelector,
		To: reference.To{
			List:    &CosmoNamespaceList{},
			Managed: &CosmoNamespace{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.Namespace")
	}
	mg.Spec.ForProvider.Namespace = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.NamespaceRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.BaseSubgraphName),
		Extract:      resource.ExtractParamPath("name", false),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.BaseSubgraphRef,
		Selector:     mg.Spec.InitProvider.BaseSubgraphSelector,
		To: reference.To{
			List:    &SubgraphList{},
			Managed: &Subgraph{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.BaseSubgraphName")
	}
	mg.Spec.InitProvider.BaseSubgraphName = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.BaseSubgraphRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Namespace),
		Extract:      resource.ExtractParamPath("name", false),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.NamespaceRef,
		Selector:     mg.Spec.InitProvider.NamespaceSelector,
		To: reference.To{
			List:    &CosmoNamespaceList{},
			Managed: &CosmoNamespace{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.Namespace")
	}
	mg.Spec.InitProvider.Namespace = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.NamespaceRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this FederatedGraph.
func (mg *FederatedGraph) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Namespace),
		Extract:      resource.ExtractParamPath("name", false),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.NamespaceRef,
		Selector:     mg.Spec.ForProvider.NamespaceSelector,
		To: reference.To{
			List:    &CosmoNamespaceList{},
			Managed: &CosmoNamespace{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.Namespace")
	}
	mg.Spec.ForProvider.Namespace = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.NamespaceRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Namespace),
		Extract:      resource.ExtractParamPath("name", false),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.NamespaceRef,
		Selector:     mg.Spec.InitProvider.NamespaceSelector,
		To: reference.To{
			List:    &CosmoNamespaceList{},
			Managed: &CosmoNamespace{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.Namespace")
	}
	mg.Spec.InitProvider.Namespace = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.NamespaceRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this Monograph.
func (mg *Monograph) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Namespace),
		Extract:      resource.ExtractParamPath("name", false),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.NamespaceRef,
		Selector:     mg.Spec.ForProvider.NamespaceSelector,
		To: reference.To{
			List:    &CosmoNamespaceList{},
			Managed: &CosmoNamespace{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.Namespace")
	}
	mg.Spec.ForProvider.Namespace = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.NamespaceRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Namespace),
		Extract:      resource.ExtractParamPath("name", false),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.NamespaceRef,
		Selector:     mg.Spec.InitProvider.NamespaceSelector,
		To: reference.To{
			List:    &CosmoNamespaceList{},
			Managed: &CosmoNamespace{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.Namespace")
	}
	mg.Spec.InitProvider.Namespace = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.NamespaceRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this PersistedOperations.
func (mg *PersistedOperations) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.FederatedGraphName),
		Extract:      resource.ExtractParamPath("name", false),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.FederatedGraphRef,
		Selector:     mg.Spec.ForProvider.FederatedGraphSelector,
		To: reference.To{
			List:    &FederatedGraphList{},
			Managed: &FederatedGraph{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.FederatedGraphName")
	}
	mg.Spec.ForProvider.FederatedGraphName = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.FederatedGraphRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Namespace),
		Extract:      resource.ExtractParamPath("name", false),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.NamespaceRef,
		Selector:     mg.Spec.ForProvider.NamespaceSelector,
		To: reference.To{
			List:    &CosmoNamespaceList{},
			Managed: &CosmoNamespace{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.Namespace")
	}
	mg.Spec.ForProvider.Namespace = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.NamespaceRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.FederatedGraphName),
		Extract:      resource.ExtractParamPath("name", false),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.FederatedGraphRef,
		Selector:     mg.Spec.InitProvider.FederatedGraphSelector,
		To: reference.To{
			List:    &FederatedGraphList{},
			Managed: &FederatedGraph{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.FederatedGraphName")
	}
	mg.Spec.InitProvider.FederatedGraphName = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.FederatedGraphRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Namespace),
		Extract:      resource.ExtractParamPath("name", false),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.NamespaceRef,
		Selector:     mg.Spec.InitProvider.NamespaceSelector,
		To: reference.To{
			List:    &CosmoNamespaceList{},
			Managed: &CosmoNamespace{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.Namespace")
	}
	mg.Spec.InitProvider.Namespace = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.NamespaceRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this RouterToken.
func (mg *RouterToken) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.GraphName),
		Extract:      resource.ExtractParamPath("name", false),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.GraphRef,
		Selector:     mg.Spec.ForProvider.GraphSelector,
		To: reference.To{
			List:    &FederatedGraphList{},
			Managed: &FederatedGraph{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.GraphName")
	}
	mg.Spec.ForProvider.GraphName = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.GraphRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Namespace),
		Extract:      resource.ExtractParamPath("name", false),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.NamespaceRef,
		Selector:     mg.Spec.ForProvider.NamespaceSelector,
		To: reference.To{
			List:    &CosmoNamespaceList{},
			Managed: &CosmoNamespace{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.Namespace")
	}
	mg.Spec.ForProvider.Namespace = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.NamespaceRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.GraphName),
		Extract:      resource.ExtractParamPath("name", false),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.GraphRef,
		Selector:     mg.Spec.InitProvider.GraphSelector,
		To: reference.To{
			List:    &FederatedGraphList{},
			Managed: &FederatedGraph{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.GraphName")
	}
	mg.Spec.InitProvider.GraphName = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.GraphRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Namespace),
		Extract:      resource.ExtractParamPath("name", false),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.NamespaceRef,
		Selector:     mg.Spec.InitProvider.NamespaceSelector,
		To: reference.To{
			List:    &CosmoNamespaceList{},
			Managed: &CosmoNamespace{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.Namespace")
	}
	mg.Spec.InitProvider.Namespace = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.NamespaceRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this Subgraph.
func (mg *Subgraph) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Namespace),
		Extract:      resource.ExtractParamPath("name", false),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.NamespaceRef,
		Selector:     mg.Spec.ForProvider.NamespaceSelector,
		To: reference.To{
			List:    &CosmoNamespaceList{},
			Managed: &CosmoNamespace{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.Namespace")
	}
	mg.Spec.ForProvider.Namespace = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.NamespaceRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Namespace),
		Extract:      resource.ExtractParamPath("name", false),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.NamespaceRef,
		Selector:     mg.Spec.InitProvider.NamespaceSelector,
		To: reference.To{
			List:    &CosmoNamespaceList{},
			Managed: &CosmoNamespace{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.Namespace")
	}
	mg.Spec.InitProvider.Namespace = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.NamespaceRef = rsp.ResolvedReference

	return nil
}
