// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type MonographInitParameters struct {

	// (String) The admission webhook secret for the monograph.
	// The admission webhook secret for the monograph.
	AdmissionWebhookSecretSecretRef *v2.SecretKeySelector `json:"admissionWebhookSecretSecretRef,omitempty" tf:"-"`

	// (String) The admission webhook URL for the monograph.
	// The admission webhook URL for the monograph.
	AdmissionWebhookURL *string `json:"admissionWebhookUrl,omitempty" tf:"admission_webhook_url,omitempty"`

	// (String) The GraphQL endpoint URL of the monograph.
	// The GraphQL endpoint URL of the monograph.
	GraphURL *string `json:"graphUrl,omitempty" tf:"graph_url,omitempty"`

	// (String) The name of the monograph.
	// The name of the monograph.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The namespace in which the monograph is located.
	// The namespace in which the monograph is located.
	// +crossplane:generate:reference:type=github.com/web-seven/provider-wundergraph-cosmo/apis/cluster/graph/v1alpha1.CosmoNamespace
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("name",false)
	// +crossplane:generate:reference:refFieldName=NamespaceRef
	// +crossplane:generate:reference:selectorFieldName=NamespaceSelector
	Namespace *string `json:"namespace,omitempty" tf:"namespace,omitempty"`

	// Reference to a CosmoNamespace in graph to populate namespace.
	// +kubebuilder:validation:Optional
	NamespaceRef *v2.Reference `json:"namespaceRef,omitempty" tf:"-"`

	// Selector for a CosmoNamespace in graph to populate namespace.
	// +kubebuilder:validation:Optional
	NamespaceSelector *v2.Selector `json:"namespaceSelector,omitempty" tf:"-"`

	// (String) The readme for the subgraph.
	// The readme for the subgraph.
	Readme *string `json:"readme,omitempty" tf:"readme,omitempty"`

	// (String) The routing URL for the monograph.
	// The routing URL for the monograph.
	RoutingURL *string `json:"routingUrl,omitempty" tf:"routing_url,omitempty"`

	// (String) The schema for the subgraph.
	// The schema for the subgraph.
	Schema *string `json:"schema,omitempty" tf:"schema,omitempty"`

	// (String) The subscription protocol for the subgraph.
	// The subscription protocol for the subgraph.
	SubscriptionProtocol *string `json:"subscriptionProtocol,omitempty" tf:"subscription_protocol,omitempty"`

	// (String) The subscription URL for the subgraph.
	// The subscription URL for the subgraph.
	SubscriptionURL *string `json:"subscriptionUrl,omitempty" tf:"subscription_url,omitempty"`

	// (String) The websocket subprotocol for the subgraph.
	// The websocket subprotocol for the subgraph.
	WebsocketSubprotocol *string `json:"websocketSubprotocol,omitempty" tf:"websocket_subprotocol,omitempty"`
}

type MonographObservation struct {

	// (String) The admission webhook URL for the monograph.
	// The admission webhook URL for the monograph.
	AdmissionWebhookURL *string `json:"admissionWebhookUrl,omitempty" tf:"admission_webhook_url,omitempty"`

	// (String) The GraphQL endpoint URL of the monograph.
	// The GraphQL endpoint URL of the monograph.
	GraphURL *string `json:"graphUrl,omitempty" tf:"graph_url,omitempty"`

	// (String) The unique identifier of the monograph resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) The name of the monograph.
	// The name of the monograph.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The namespace in which the monograph is located.
	// The namespace in which the monograph is located.
	Namespace *string `json:"namespace,omitempty" tf:"namespace,omitempty"`

	// (String) The readme for the subgraph.
	// The readme for the subgraph.
	Readme *string `json:"readme,omitempty" tf:"readme,omitempty"`

	// (String) The routing URL for the monograph.
	// The routing URL for the monograph.
	RoutingURL *string `json:"routingUrl,omitempty" tf:"routing_url,omitempty"`

	// (String) The schema for the subgraph.
	// The schema for the subgraph.
	Schema *string `json:"schema,omitempty" tf:"schema,omitempty"`

	// (String) The subscription protocol for the subgraph.
	// The subscription protocol for the subgraph.
	SubscriptionProtocol *string `json:"subscriptionProtocol,omitempty" tf:"subscription_protocol,omitempty"`

	// (String) The subscription URL for the subgraph.
	// The subscription URL for the subgraph.
	SubscriptionURL *string `json:"subscriptionUrl,omitempty" tf:"subscription_url,omitempty"`

	// (String) The websocket subprotocol for the subgraph.
	// The websocket subprotocol for the subgraph.
	WebsocketSubprotocol *string `json:"websocketSubprotocol,omitempty" tf:"websocket_subprotocol,omitempty"`
}

type MonographParameters struct {

	// (String) The admission webhook secret for the monograph.
	// The admission webhook secret for the monograph.
	// +kubebuilder:validation:Optional
	AdmissionWebhookSecretSecretRef *v2.SecretKeySelector `json:"admissionWebhookSecretSecretRef,omitempty" tf:"-"`

	// (String) The admission webhook URL for the monograph.
	// The admission webhook URL for the monograph.
	// +kubebuilder:validation:Optional
	AdmissionWebhookURL *string `json:"admissionWebhookUrl,omitempty" tf:"admission_webhook_url,omitempty"`

	// (String) The GraphQL endpoint URL of the monograph.
	// The GraphQL endpoint URL of the monograph.
	// +kubebuilder:validation:Optional
	GraphURL *string `json:"graphUrl,omitempty" tf:"graph_url,omitempty"`

	// (String) The name of the monograph.
	// The name of the monograph.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The namespace in which the monograph is located.
	// The namespace in which the monograph is located.
	// +crossplane:generate:reference:type=github.com/web-seven/provider-wundergraph-cosmo/apis/cluster/graph/v1alpha1.CosmoNamespace
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("name",false)
	// +crossplane:generate:reference:refFieldName=NamespaceRef
	// +crossplane:generate:reference:selectorFieldName=NamespaceSelector
	// +kubebuilder:validation:Optional
	Namespace *string `json:"namespace,omitempty" tf:"namespace,omitempty"`

	// Reference to a CosmoNamespace in graph to populate namespace.
	// +kubebuilder:validation:Optional
	NamespaceRef *v2.Reference `json:"namespaceRef,omitempty" tf:"-"`

	// Selector for a CosmoNamespace in graph to populate namespace.
	// +kubebuilder:validation:Optional
	NamespaceSelector *v2.Selector `json:"namespaceSelector,omitempty" tf:"-"`

	// (String) The readme for the subgraph.
	// The readme for the subgraph.
	// +kubebuilder:validation:Optional
	Readme *string `json:"readme,omitempty" tf:"readme,omitempty"`

	// (String) The routing URL for the monograph.
	// The routing URL for the monograph.
	// +kubebuilder:validation:Optional
	RoutingURL *string `json:"routingUrl,omitempty" tf:"routing_url,omitempty"`

	// (String) The schema for the subgraph.
	// The schema for the subgraph.
	// +kubebuilder:validation:Optional
	Schema *string `json:"schema,omitempty" tf:"schema,omitempty"`

	// (String) The subscription protocol for the subgraph.
	// The subscription protocol for the subgraph.
	// +kubebuilder:validation:Optional
	SubscriptionProtocol *string `json:"subscriptionProtocol,omitempty" tf:"subscription_protocol,omitempty"`

	// (String) The subscription URL for the subgraph.
	// The subscription URL for the subgraph.
	// +kubebuilder:validation:Optional
	SubscriptionURL *string `json:"subscriptionUrl,omitempty" tf:"subscription_url,omitempty"`

	// (String) The websocket subprotocol for the subgraph.
	// The websocket subprotocol for the subgraph.
	// +kubebuilder:validation:Optional
	WebsocketSubprotocol *string `json:"websocketSubprotocol,omitempty" tf:"websocket_subprotocol,omitempty"`
}

// MonographSpec defines the desired state of Monograph
type MonographSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   MonographParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider MonographInitParameters `json:"initProvider,omitempty"`
}

// MonographStatus defines the observed state of Monograph.
type MonographStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               MonographObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Monograph is the Schema for the Monographs API. A monograph is a resource that represents a single subgraph with GraphQL Federation disabled. For more information on monographs, please refer to the Cosmo Documentation https://cosmo-docs.wundergraph.com/cli/monograph.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,cosmo}
type Monograph struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.graphUrl) || (has(self.initProvider) && has(self.initProvider.graphUrl))",message="spec.forProvider.graphUrl is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.routingUrl) || (has(self.initProvider) && has(self.initProvider.routingUrl))",message="spec.forProvider.routingUrl is a required parameter"
	Spec   MonographSpec   `json:"spec"`
	Status MonographStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// MonographList contains a list of Monographs
type MonographList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Monograph `json:"items"`
}

// Repository type metadata.
var (
	Monograph_Kind             = "Monograph"
	Monograph_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Monograph_Kind}.String()
	Monograph_KindAPIVersion   = Monograph_Kind + "." + CRDGroupVersion.String()
	Monograph_GroupVersionKind = CRDGroupVersion.WithKind(Monograph_Kind)
)

func init() {
	SchemeBuilder.Register(&Monograph{}, &MonographList{})
}
