// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type RouterTokenInitParameters struct {

	// (String) The name of the graph to create the token for.
	// The name of the graph to create the token for.
	// +crossplane:generate:reference:type=github.com/web-seven/provider-wundergraph-cosmo/apis/cluster/graph/v1alpha1.FederatedGraph
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("name",false)
	// +crossplane:generate:reference:refFieldName=GraphRef
	// +crossplane:generate:reference:selectorFieldName=GraphSelector
	GraphName *string `json:"graphName,omitempty" tf:"graph_name,omitempty"`

	// Reference to a FederatedGraph in graph to populate graphName.
	// +kubebuilder:validation:Optional
	GraphRef *v2.Reference `json:"graphRef,omitempty" tf:"-"`

	// Selector for a FederatedGraph in graph to populate graphName.
	// +kubebuilder:validation:Optional
	GraphSelector *v2.Selector `json:"graphSelector,omitempty" tf:"-"`

	// (String) The name of the router token.
	// The name of the router token.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The namespace to create the token in.
	// The namespace to create the token in.
	// +crossplane:generate:reference:type=github.com/web-seven/provider-wundergraph-cosmo/apis/cluster/graph/v1alpha1.CosmoNamespace
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("name",false)
	// +crossplane:generate:reference:refFieldName=NamespaceRef
	// +crossplane:generate:reference:selectorFieldName=NamespaceSelector
	Namespace *string `json:"namespace,omitempty" tf:"namespace,omitempty"`

	// Reference to a CosmoNamespace in graph to populate namespace.
	// +kubebuilder:validation:Optional
	NamespaceRef *v2.Reference `json:"namespaceRef,omitempty" tf:"-"`

	// Selector for a CosmoNamespace in graph to populate namespace.
	// +kubebuilder:validation:Optional
	NamespaceSelector *v2.Selector `json:"namespaceSelector,omitempty" tf:"-"`
}

type RouterTokenObservation struct {

	// (String) The name of the graph to create the token for.
	// The name of the graph to create the token for.
	GraphName *string `json:"graphName,omitempty" tf:"graph_name,omitempty"`

	// (String) The unique identifier of the router token.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) The name of the router token.
	// The name of the router token.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The namespace to create the token in.
	// The namespace to create the token in.
	Namespace *string `json:"namespace,omitempty" tf:"namespace,omitempty"`
}

type RouterTokenParameters struct {

	// (String) The name of the graph to create the token for.
	// The name of the graph to create the token for.
	// +crossplane:generate:reference:type=github.com/web-seven/provider-wundergraph-cosmo/apis/cluster/graph/v1alpha1.FederatedGraph
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("name",false)
	// +crossplane:generate:reference:refFieldName=GraphRef
	// +crossplane:generate:reference:selectorFieldName=GraphSelector
	// +kubebuilder:validation:Optional
	GraphName *string `json:"graphName,omitempty" tf:"graph_name,omitempty"`

	// Reference to a FederatedGraph in graph to populate graphName.
	// +kubebuilder:validation:Optional
	GraphRef *v2.Reference `json:"graphRef,omitempty" tf:"-"`

	// Selector for a FederatedGraph in graph to populate graphName.
	// +kubebuilder:validation:Optional
	GraphSelector *v2.Selector `json:"graphSelector,omitempty" tf:"-"`

	// (String) The name of the router token.
	// The name of the router token.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The namespace to create the token in.
	// The namespace to create the token in.
	// +crossplane:generate:reference:type=github.com/web-seven/provider-wundergraph-cosmo/apis/cluster/graph/v1alpha1.CosmoNamespace
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("name",false)
	// +crossplane:generate:reference:refFieldName=NamespaceRef
	// +crossplane:generate:reference:selectorFieldName=NamespaceSelector
	// +kubebuilder:validation:Optional
	Namespace *string `json:"namespace,omitempty" tf:"namespace,omitempty"`

	// Reference to a CosmoNamespace in graph to populate namespace.
	// +kubebuilder:validation:Optional
	NamespaceRef *v2.Reference `json:"namespaceRef,omitempty" tf:"-"`

	// Selector for a CosmoNamespace in graph to populate namespace.
	// +kubebuilder:validation:Optional
	NamespaceSelector *v2.Selector `json:"namespaceSelector,omitempty" tf:"-"`
}

// RouterTokenSpec defines the desired state of RouterToken
type RouterTokenSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   RouterTokenParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider RouterTokenInitParameters `json:"initProvider,omitempty"`
}

// RouterTokenStatus defines the observed state of RouterToken.
type RouterTokenStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               RouterTokenObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// RouterToken is the Schema for the RouterTokens API. Generates a token that is limited to a federated graph. This token allows the router to interact with the platform and send metrics to the collectors. For more information on router tokens, please refer to the Cosmo Documentation https://cosmo-docs.wundergraph.com/cli/router/token/create.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,cosmo}
type RouterToken struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   RouterTokenSpec   `json:"spec"`
	Status RouterTokenStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// RouterTokenList contains a list of RouterTokens
type RouterTokenList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []RouterToken `json:"items"`
}

// Repository type metadata.
var (
	RouterToken_Kind             = "RouterToken"
	RouterToken_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: RouterToken_Kind}.String()
	RouterToken_KindAPIVersion   = RouterToken_Kind + "." + CRDGroupVersion.String()
	RouterToken_GroupVersionKind = CRDGroupVersion.WithKind(RouterToken_Kind)
)

func init() {
	SchemeBuilder.Register(&RouterToken{}, &RouterTokenList{})
}
